### ISSUE TITLE
Guidelines about File format

### ISSUE THREAD

**Issue by floradanna** [elixir-europe/rdmkit#1025]
**Link to the page of interest**
https://rdmkit.elixir-europe.org/data_organisation

[Google doc from WP1](https://docs.google.com/document/d/1VlfrnI77iDhU9bQwqx-ynJsNLie9Uf4o8Ee97B9wfNU/edit#heading=h.58yb4u5em02r). Follow-up to F2F meeting in Padova.

**Describe what you would change to the page**
Add best practices about file formats: How do you choose file formats?
Considerations: instrument/machine/software constrains or limitations; how do you know if a format is open or proprietary?
Solutions: where and how to find recommended file formats (open, non proprietary), converting into open format by X tool, etc

**List the tool(s)or resource(s) that are missing on the page (if applicable)**
- Name
- Link
- Description
- Registry (biotools or/and FAIRsharing ID) (optional)

**Comment by bedroesb** [comment]
@ivanmicetic Do you have all the information to move forward?

**Comment by ivanmicetic** [comment]
This has been solved during the RDMkit Contentathon with PR https://github.com/elixir-europe/rdmkit/pull/1250.
