### ISSUE TITLE
Moving Information Security content to a more general page

### ISSUE THREAD

**Issue by nicjar** [elixir-europe/rdmkit#1026]
**Link to the page of interest**
https://rdmkit.elixir-europe.org/human_data#processing-and-analysing-human-research-data

**Describe what you would change to the page**
[Google Doc from WP1](https://docs.google.com/document/d/1a133hm7SaWJQXor0_5MW1KWiWgnT5u4IU2rwQduR0rU/edit). Follow-up from F2F meeting in Padova.

The _Human data_ page has a brief description of **Information Security** principles. However, the Information security principles are relevant for **all** types of data, not only human data. 

Suggestion is to move (and slightly expand) the Information Security content to a more generic relevant page.

_Options_:
- Data protection page (task)
  - Focus on the legal Personal Data Protection (GDPR) aspect at the moment. However, the term *Data Protection* has a more precise legal definition that might not be obvious to all, but might rather be interpreted as protecting (any) data from harm. 
- Data analysis page (task)
  - Nothing about systems for analysis
- Processing (life cycle)
  - Nothing about systems for processing, Also, Information Security is of relevance during several life cycle stages.
- Analysing (life cycle)
  - Nothing about systems for analysing. Also, Information Security is of relevance during several life cycle stages.
- Preserving (life cycle)
  - Touches on aspects of Information Security, but it can be conceived as being only one part of the life cycle. Also, Information Security is of relevance during several life cycle stages.
- Write a new Information Security page?
  - A lot of in-depth information available elsewhere, unnecessary to repeat.
  - Relevant content could be kept quite short and then refer to other resources

_Possible solution_:
- Rename the *Data protection* page to _Protecting data_, and have it contain both the legal (Personal Data Protection), and the technical/procedural Information Security aspects.

**Comment by floradanna** [comment]
It's a quite complex topic. What if we start from the questions we would like to answer? Would that help with figuring out what goes where? for instance,

What are best practices for information security (IS) in RDM?
How can you implement IS practices in your research institute? (for data stewards, of course).
What policies should be established for IS in RDM?
What tools or technique can you use for implementing IS in RDM?

Which of these or other questions would be mainly addressed?

**Comment by nicjar** [comment]
Yes, it's a complex topic, and I don't think it should be addressed in _detail_ in the RDMkit. But I think that we describe the general principles so that a DS or researcher becomes aware that there are a lot of good practices thought out about this, so that they can better engage with relevant local resources/experts (university IT departments, service providers, etc).

**Comment by CaroleGoble** [comment]
I have access to national TRE folks in the UK - its human data though. I can ask HDR-UK to write the pages....

**Comment by bedroesb** [comment]
Thanks a lot!
