### ISSUE TITLE
Planning doesn't even mentin DSW

### ISSUE THREAD

**Issue by CaroleGoble** [elixir-europe/rdmkit#1031]
**Link to the page of interest**
 https://rdmkit.elixir-europe.org/planning  

**Describe what you would change to the page**

doesn't have a link or even mention DSW or point to any planning tools

**Comment by Nazeeefa** [comment]
Thanks @CaroleGoble for mentioning this.
To page contributors (@bianchini88, @floradanna, @korbinib, @siirif, @minnami) and @bedroesb: it may be helpful to also provide the table for 'Relevant Tools and Resources' for each data life cycle stage pages.

**Comment by bedroesb** [comment]
Something for in the editorial meeting to be discussed, but a reminder that we already discussed this in the past and we decided that: the data life cycle pages (general introduction/overview) have the equivalent task page that goes more in detail. In the case of Planning, the DMP task page DOES link to DSW.

**Comment by bedroesb** [comment]
Planning got update in #1082 and the goal is still to not link to tools in the data life cycle pages, but rather to improve the visibility of the related pages so people end up on data management plant where tools are listed!
