### ISSUE TITLE
adding damap to DMP tools

### ISSUE THREAD

**Issue by floradanna** [elixir-europe/rdmkit#1054]
Good morning all,

A suggestion: adding  https://damap.org/  (U Wien, Austria) to the list of DMP tools available.
Thanks!
Have a great day,
Paulette.

**Comment by bedroesb** [comment]
What do you think of this Description:
DAMAP guides you step by step through a DMP and lets you export a pre-filled DMP as a Word document that you can customize and use for submission to funders. DAMAP is open source and to be self deployed.

**Comment by floradanna** [comment]
I don't know.
Maybe @froggypaule can help with this.

**Comment by froggypaule** [comment]
Hello @bedroesb :

DAMAP is an open source DMP tool from TU Wien. It guides you step by step through a DMP and lets you export a pre-filled DMP as a Word document that you can customize and use for submission to funders. Also, DAMAP is compatible with the RDA recommendation for machine-actionable DMPs and offers an export of JSON DMPs.


thanks!

**Comment by froggypaule** [comment]
ooops, I wouldn't know honestly re an instance. I guess not; from https://github.com/tuwien-csd/damap-backend one has to install it first.
For the affiliation, of course, you know best!
Sorry not to be more helpful...

**Comment by bedroesb** [comment]
Tools got updated, thanks to all for chipping in!
