### ISSUE TITLE
MOLGENIS tool assembly page

### ISSUE THREAD

**Issue by korbinib** [elixir-europe/rdmkit#1070]
**What topic do you wish to add?**
MOLGENIS tool assembly page

**Are there existing pages in the RDMkit website related to the requested page?**
data analysis, data publication, storage, data quality, data transfer, metadata, sensitive data

**Resources**
If there are there resources that could be utilised for writing the new page, please list them below:
MOLGENIS

**Context**
If this request is coming from a particular project, domain, or use-case please list them below:
RDMkit editorial meeting 2022-09-30

PR #1069

**Comment by bedroesb** [comment]
this page is merged and live
