### ISSUE TITLE
Update requests: Bioimaging data

### ISSUE THREAD

**Issue by daniwelter** [elixir-europe/rdmkit#1102]
I would like to request the following updates to the Bioimaging data page at `/bioimaging_data`:
- links to Zeiss library and Metatadata Standards Directory WG point to outdated pages so the user has to click on yet another link. Please update to the correct repo
  - Metadata standards directory is hard to navigate - consider a FAIRsharing collection 
- replace "see below" with in-page tags
- "What constitutes bioimaging data" should include some concrete examples of image types and formats
- "What constitutes bioimaging data" and "Data management challenges" paragraphs are virtually identical - please remove duplication
- Review bullet point lists against style guide (inconsistent punctuation)

**Comment by jburel** [comment]
Looking into it

**Comment by jburel** [comment]
Will it possible to assign it to my. I cannot add myself as assignee
