### ISSUE TITLE
Define etc. style

### ISSUE THREAD

**Issue by marina-popleteeva** [elixir-europe/rdmkit#1106]
**Description**
*et cetera* is short form *etc.* and should be followed by period [regardless of any additional punctuation that may follow](https://www.btb.termiumplus.gc.ca/tpv2guides/guides/wrtps/index-eng.html?lang=eng&lettr=indx_catlog_e&page=9qbnz5ZJv1tw.html). So, it should be written
- ... analysis workflows, code, etc.), not on papers or articles.
- ... related to your data (GDPR, consent, patent, etc.);
- ... allowed geographical regions, allowed recipients etc.).

If @martin-nc approves, please add period in all pages, including Style guide. Add a bullet point in Style guide about "etc." (right now it is used there without period but not explained/considered).

P.s. The list in this issue does not follow style guide ;)

**Comment by martin-nc** [comment]
Closing this, then. The [website style guide](https://rdmkit.elixir-europe.org/style_guide) gives a few basic pointers, but for more details we use the EC style guides linked to from the top of that page.
