### ISSUE TITLE
Update requests Rare disease page

### ISSUE THREAD

**Issue by pinarpink** [elixir-europe/rdmkit#1112]
Based upon my review of the page according to the provided checklist. I'd request the following updates:

- There are sentences that start with "we recommend" these should be changed with "it is recommended that" or "this community recommends" or similar.
- Roles for reare disease data FAIrification is identified, the so called "three-party collaboration setup". It woul dto good to describe how those roles are related to the [data steward roles](https://rdmkit.elixir-europe.org/your_role) identified by RDMkit.

**Comment by PhilipvD** [comment]
Done. Please see PRs https://github.com/elixir-europe/rdmkit/pull/1160 and https://github.com/elixir-europe/rdmkit/pull/1110.

**Comment by bedroesb** [comment]
Great!
