### ISSUE TITLE
Update request Plant sciences page

### ISSUE THREAD

**Issue by pinarpink** [elixir-europe/rdmkit#1114]
Based on my quick review of the Plant sciences:

The tools PLAZA and PHIS are not described in the text but they exist in the tools table. They need to be added to the text. Also PIPPA is listed as a national resource for Belgium but not described in the Plants page. So  the generic PIPPA description could be added to the Plants page.

**Comment by bedroesb** [comment]
Hey Pinar! This came to be because of the assemblies where these tools are part of, were added after the plant sciences page. But This problem will be solved on its own when we move to the new way of tagging tools
