### ISSUE TITLE
New resource to be added to the UK National resources page

### ISSUE THREAD

**Issue by pinarpink** [elixir-europe/rdmkit#1122]
- [The 5 safes framework](https://ukdataservice.ac.uk/help/secure-lab/what-is-the-five-safes-framework/ ) to be added to the [UK national page](https://rdmkit.elixir-europe.org/uk_resources) 
- It this resource is also availble to other countries then it could also be mentioned as a solution in the [sensitive data](https://rdmkit.elixir-europe.org/sensitive_data) and/or [human data](https://rdmkit.elixir-europe.org/human_data) pages.

**Comment by bedroesb** [comment]
@smza Do I tag you for this? :)

**Comment by smza** [comment]
> @smza Do I tag you for this? :)

yes please @bedroesb  ;)

@smza

**Comment by robertmand** [comment]
Hi , thanks pinar, “5 safes”  It is already on the UK page with the original ONS URL.
My belief is that it is a UK resource (though should be international).

**Comment by bedroesb** [comment]
Since the UK resource is added to the UK page I think we can close this issue!
