### ISSUE TITLE
Make national resource page more visible

### ISSUE THREAD

**Issue by Nazeeefa** [elixir-europe/rdmkit#1123]
National resource page for a country itself is not so visibly mentioned under relevant pages. The only way to find a link to a national resource page is when you click on 'View national resources' and hover over a flag icon. This is subtle and can be hard to find or easily missed. See gif attached (showing part of 'NeLS' tool assembly page).
![national_resources](https://user-images.githubusercontent.com/6730853/206436642-842aa8ef-9847-49ce-9261-a83b19690cd7.gif)

**Suggested solution**
Mention link to country page in the bar (space highlighted in screenshot below) when national resources are from one country, otherwise mention link to 'National resources' section (when national resources from multiple countries are mentioned):
<img width="894" alt="Screenshot 2022-12-08 at 12 36 32" src="https://user-images.githubusercontent.com/6730853/206437304-763e93bb-53a4-4f78-86f9-6943cfc897ae.png">
It could also be useful to make 'View national resources' button more visible by perhaps adding flag icon to the button itself?

**Comment by bianchini88** [comment]
This is particularly relevant for "national" tool assemblies.

**Comment by korbinib** [comment]
Could there be a way to trigger the expansion through a flag/setting?

**Comment by bedroesb** [comment]
This should be possible! I started a while ago with experimenting in how we could improve this: https://github.com/ELIXIR-Belgium/elixir-toolkit-theme/pull/119

**Comment by bedroesb** [comment]
@Nazeeefa 
> Mention link to country page in the bar (space highlighted in screenshot below):

Do you mean the overview page with all countries?

**Comment by bedroesb** [comment]
National resources have now their own subheading so it is more visible than ever! I will close this issue since #1366 is merged, thanks for bringing this up!

**Comment by bedroesb** [comment]
Well based on your suggestion in this issue and the screenshot in your description, you can see it was just a button before and it used to be a part of the existing table, and now it has its own H3 heading + its own table :sweat_smile:
