### ISSUE TITLE
Issue on page: Compliance monitoring & measurement

### ISSUE THREAD

**Issue by froggypaule** [elixir-europe/rdmkit#1124]
I would like to report an issue on the Compliance monitoring & measurement page at `/compliance_monitoring`. Description of the issue:

Hello to the authors of this page, @pinarpink and the others (whom unfortunately I don't know so well). I also ping here @KarelBerka; further I refer to #616. 

Following the WP1 F2F at Padova, we chose a few topics we thought would warrant a review of in the RDMkit. I assigned myself to have a look at 'ethics'. Karel has joined me in this job as well. 
I consequently reviewed all mentions of ethics in the RDMkit, and I have a few revisions to make here and there (which I haven't posted as yet). 
Following this work, it seems to me that a specific page on 'ethics' is warranted: ethics is a term that comes up all over the place, but nowhere is it 'defined' properly while put together with the GDPR for example. We need to say that ethics is not the same thing as the GDPR.
Following @floradanna 's suggestion I rethought the issue from a task perspective way; hence my focus on the cited page. 

Imho this page has one problem: it mixes 'compliance monitoring' with 'compliance measuring'; I find it difficult to read: it took me a while to understand that the first section `/compliance_monitoring#how-can-you-measure-and-document-data-management-capabilities` actually talked about evaluation. This is why I propose the following:

- create a new page called 'data management evaluation' (or 'FAIR evaluation' ?) that would then include the section  `/compliance_monitoring#how-can-you-measure-and-document-data-management-capabilities`  and all other items relevant to evaluation
- create a new page called 'ethical monitoring' that would define the context etc... this is the page I would call 'ethics' 
- as for the section `/compliance_monitoring#how-can-you-ethically-access-genetic-resources-of-another-country` just now I don't know how to place it in this new configuration...

Mind you I  haven't yet started on the  'ethical monitoring' page. This is still TBD. But I thought that I share these thoughts with you in the first place. Thanks! and thanks to @bianchini88 to guiding me in how to do this.

**Comment by froggypaule** [comment]
Hello there!
Now that we are working actively on #616, I once more want to point out an issue (I think) with the https://rdmkit.elixir-europe.org/compliance_monitoring page: 

1. the first question` /compliance_monitoring#how-can-you-measure-and-document-data-management-capabilities` talks about FAIR evaluation: imho, this warrants its own page as FAIR evaluation is becoming quite a hot topic
2. the second question ` /compliance_monitoring#how-can-you-ethically-access-genetic-resources-of-another-country` will need to be included elsewhere? maybe simply in the 'new' ethics page? could be an option.

**Comment by froggypaule** [comment]
@pinarpink : you are one of the authors de this page, do you think the second question `/compliance_monitoring#how-can-you-ethically-access-genetic-resources-of-another-country` could go as is in the new ethics page being written now?

**Comment by pinarpink** [comment]
@froggypaule I am so sorry for the delay in my response. yes, `/compliance_monitoring#how-can-you-ethically-access-genetic-resources-of-another-country` can safely go into the Ethics page. We can then put the remaining material under "data management evaluation" or "FAIR evaluation," as suggested. There are a few bullets on infosec, these could go under the relevant page.

**Comment by froggypaule** [comment]
Hello all, @pinarpink : it has been a while so that I have forgotten how to navigate the github process wrt rdmkit. Maybe @korbinib can help here? (on my own I'll end up nowhere...).
Many thanks all.

**Comment by floradanna** [comment]
Hi @froggypaule, apologies for the late response. Are you still in need of technical help? Please, let us know

**Comment by korbinib** [comment]
fixed by #1375 ?

**Comment by korbinib** [comment]
fixed by #1375  ?
