### ISSUE TITLE
National page for Slovenia

### ISSUE THREAD

**Issue by bianchini88** [elixir-europe/rdmkit#1126]
**National page for Slovenia**

**Context**
From discussion on virtual track at the December hackathon.

**Comment by Nazeeefa** [comment]
Thanks @bianchini88 Here's the page ready to be filled:

RDM in Slovenia https://github.com/elixir-europe/rdmkit/blob/master/pages/national_resources/si_resources.md (thanks @bedroesb for creating this!)

Are there existing pages in the RDMkit website related to the requested page?
No

Could you kindly fill out the following information?
**Resources**
If there are resources that could be utilised for writing the new page, please list them below:

**Context**
Mention who requested the national page for Cyprus?

**Comment by Nazeeefa** [comment]
I think information on who will be working on this page and contributing is important, so editors can stay in touch and provide feedback to the page contributors via GitHub easily.

**Comment by bianchini88** [comment]
The person did not provide any GitHub details, email address or other contact information, and I do not feel like writing down the name only for the sake of it.

**Comment by bianchini88** [comment]
> @bianchini88 will reach out to Marko Vidak
Done!
