### ISSUE TITLE
Sensitive data and Data protection cross reference

### ISSUE THREAD

**Issue by pinarpink** [elixir-europe/rdmkit#1129]
Sensitive data and Data protection pages should cross reference each other in the related poages section.

**Comment by bedroesb** [comment]
If I recall correctly, the rules we settled on https://rdmkit.elixir-europe.org/editorial_board_guide#related-pages only allows the linking towards tool assemblies...

**Comment by bedroesb** [comment]
So if we want to do this we have to make it a broader discussion
