### ISSUE TITLE
Systematically harmonise "schema(s) or scheme(s)"

### ISSUE THREAD

**Issue by floradanna** [elixir-europe/rdmkit#1130]
**Link to the page of interest**
many pages

**Describe what you would change to the page**
Systematically harmonise "schema(s) or scheme(s)".

@elixir-europe/rdmkit-editors should we vote to decide which one to use?

**Comment by martin-nc** [comment]
They have slightly different meanings. "Scheme" is more of a plan, whilst "schema" can describe structure and data types within the structure e.g. a "database schema" or an "XML schema". I'm guessing it should be "schema".
