### ISSUE TITLE
link to semares broken

### ISSUE THREAD

**Issue by bianchini88** [elixir-europe/rdmkit#1132]
**Link to the page of interest**
https://docs.google.com/spreadsheets/d/16RESor_qQ_ygI0lQYHR23kbZJUobOWZUbOwhJbLptDE/edit?pli=1#gid=268211668

**Describe what you would change to the page**
I can't find anything relevant about semares. I suppose it is to be deleted,
if there is no information whatsoever about it currently available.

**Comment by bianchini88** [comment]
For documentation, this was spotted when reviewing this page https://rdmkit.elixir-europe.org/metadata_management.

**Comment by bedroesb** [comment]
@bianchini88 I guess https://www.genevention.com/products#SemaresS-area does not help much ... For me it would be ok to delete it :D

**Comment by floradanna** [comment]
I also vote for deleting it, since there is no info. Shall I delete it from the spreadsheet?

**Comment by bianchini88** [comment]
I suppose the website was down in December (or I might have made a typo when looking for this). As it is now, I suppose it can stay and we need to fix the link on the page since it brings incorrectly to https://rdmkit.elixir-europe.org/www.genevention.com/products

**Comment by bedroesb** [comment]
@floradanna and @bianchini88 I made a PR to fix the url. But we might want to question ourselves if we want this tool at all. I wonder how it ended up here. But since this is a conversation that is already initiated, lets for now just fix it and deal this together with all the other tools without context.

**Comment by bedroesb** [comment]
if one of you approves and merges this issue is dealt with ;)

**Comment by bianchini88** [comment]
I am not assigned as a reviewer, though. But you can go ahead and merge.
