### ISSUE TITLE
The Genomic Standards Consortium (GSC) on table

### ISSUE THREAD

**Issue by bianchini88** [elixir-europe/rdmkit#1138]
**Link to the page of interest**
[table](https://docs.google.com/spreadsheets/d/16RESor_qQ_ygI0lQYHR23kbZJUobOWZUbOwhJbLptDE/edit#gid=268211668)

**Describe what you would change to the page**
Is the entry "The Genomic Standards Consortium (GSC) " for the consortium (GSC) or for the standard (MIxS)? While the name of the entry refers to GSC, the hyperlink brings you to the MIxS page
and the description is for MIxS. 

I see that MIxS has a separate entry, so I suppose the hyperlink and description 
have to change to reflect that this entry is for GSC only. 

I can go ahead and change the table if somebody approves of this change.

**Comment by Nazeeefa** [comment]
For the consortium. I changed it to main website, but I think it should be linked to https://www.gensc.org/pages/about.html Thank you.

I updated the links for MIxS (and MIGS/MIMS) this morning.

**Comment by bianchini88** [comment]
Agreed, I updated the link and added a proper description.

**Comment by bedroesb** [comment]
@Nazeeefa and @bianchini88 was this solved?

**Comment by bianchini88** [comment]
Yes, this was solved.
