### ISSUE TITLE
check metadata for training in these pages

### ISSUE THREAD

**Issue by floradanna** [elixir-europe/rdmkit#1172]
**Describe the bug**
Metadata for training might be wrong in these 2 pages: provenance and dm coordination

**To Reproduce**
<img width="1148" alt="Screenshot 2023-01-13 at 13 27 06" src="https://user-images.githubusercontent.com/51486716/212320357-9f8f2077-dcaa-47c0-8e3b-a10a51c2a74b.png">

**Comment by bedroesb** [comment]
This is a problem in the theme, solution coming up
