### ISSUE TITLE
RDMkit and The Turing Way

### ISSUE THREAD

**Issue by floradanna** [elixir-europe/rdmkit#1177]
The [Turing Way website](https://the-turing-way.netlify.app/welcome.html) provides useful information about reproducibility of research project.

Although it is not life science specific, it could be useful to refer to it where needed. We could simply encourage contributors/editors to establish manual link with The Turing Way or explore the possibility for a deeper/automated integration.

Using The Turing Way could potentially prevent duplication of its content in RDMkit.

**Comment by Nazeeefa** [comment]
+1 By the way, maybe a bit off-topic, there is also a mention of RDMkit on the TW website: https://the-turing-way.netlify.app/search.html?q=RDMkit

**Comment by floradanna** [comment]
not for now
