### ISSUE TITLE
TODO: Update google docs

### ISSUE THREAD

**Issue by bedroesb** [elixir-europe/rdmkit#1179]
3 separate templates for each section, assembly, task and domain. We put them together in one folder but link to the files separately .

Editors responsible for those sections will take care of this

**Comment by lauportell** [comment]
I created this one some time ago for domain pages, maybe it helps:
https://docs.google.com/document/d/1zXY3SvUlI5EpRF8lasX4MjhMY___tDaEJ4o0JnGTqyE/edit?usp=sharing

**Comment by bedroesb** [comment]
@elixir-europe/rdmkit-editors Warm welcome to add the templates to this google drive folder: https://drive.google.com/drive/folders/1hK8jzS_MAHbOp-iBGMgreh4YYwRYDB5z for each section! People responsible for a section should know it ;)

**Comment by lauportell** [comment]
The template for domain pages is the right folder now:
https://docs.google.com/document/d/1fh8-Gq50AkXS1nhHr-gVFog-eI61dFI49nKROZlRYEQ/edit?usp=sharing

**Comment by smza** [comment]
> The template for domain pages is the right folder now:
> https://docs.google.com/document/d/1fh8-Gq50AkXS1nhHr-gVFog-eI61dFI49nKROZlRYEQ/edit?usp=sharing

Thanks @lauportell !! Cheers
