### ISSUE TITLE
Remove Ontobee from Your Tasks > Documentation and metadata?

### ISSUE THREAD

**Issue by martin-nc** [elixir-europe/rdmkit#1205]
From our "Quick suggestion" form:

> **Link to the page of interest**
> https://rdmkit.elixir-europe.org/metadata_management#how-do-you-find-appropriate-vocabularies-or-ontologies
> 
> 
> **Describe what you would change to the page**
> In this page there is a resource called Ontobee. However the resource is no longer available. I don't know if the page is down or the service is permanently offline, if it's the latter case, the resource should be removed from RDMkit.

Indeed, it doesn't seem to be there anymore. Perhaps someone knows if it has moved or disappeared?

**Comment by bedroesb** [comment]
I would remove it, the service itself is for a long time not maintained anymore: https://github.com/OntoZoo/ontobee and based on all the issues not really a trustworthy source. I will tag the contributors of this page to judge on it:

@floradanna @korbinib @marcocarraro @jmenglund @rwwh @YvonneKallberg

**Comment by YvonneKallberg** [comment]
I have no objections to remove it.

**Comment by bedroesb** [comment]
Ontobee is back online, we could keep it :thinking: Although it is not the most maintained resource ....

**Comment by rabuono** [comment]
Would [BioPortal](https://bioportal.bioontology.org/) be a good substitute?

**Comment by bedroesb** [comment]
@smza added bioportal with #1215. What do we do with this issue?

**Comment by YvonneKallberg** [comment]
I suggest the easiest solution, i.e. to close it without change, since Ontobee is up and running, and also BioPortal is added. If, in future, the issue arises again (that Ontobee is down) I guess we give up and remove it.

**Comment by bedroesb** [comment]
sounds good to me!
