### ISSUE TITLE
Useful resources

### ISSUE THREAD

**Issue by floradanna** [elixir-europe/rdmkit#1214]
**Link to the page of interest**
To be identified.

**Describe what you would change to the page**
Add the following EC resources and the related context:
- https://erc.europa.eu/sites/default/files/document/file/ERC_info_document-Open_Research_Data_and_Data_Management_Plans.pdf
- https://open-research-europe.ec.europa.eu/for-authors/data-guidelines
- [Cellosaurus](https://www.cellosaurus.org/)

**List the tool(s)or resource(s) that are missing on the page (if applicable)**
- Link: https://open-research-europe.ec.europa.eu/for-authors/data-guidelines
- Link: https://erc.europa.eu/sites/default/files/document/file/ERC_info_document-Open_Research_Data_and_Data_Management_Plans.pdf

**Comment by Nazeeefa** [comment]
Thank you @floradanna for sharing these important links! First one covers a variety of useful resources, so I think it would be helpful for a reader if we mention it in multiple pages (e.g. data management plan, etc - need to think more about which ones). The second link (https://open-research-europe.ec.europa.eu/for-authors/data-guidelines) can be mentioned in [Data publication page](https://rdmkit.elixir-europe.org/data_publication) and perhaps also in [machine_actionability page](https://rdmkit.elixir-europe.org/machine_actionability)

**Comment by floradanna** [comment]
Not for now
