### ISSUE TITLE
Issue on page: All tools and resources

### ISSUE THREAD

**Issue by mshadbolt** [elixir-europe/rdmkit#1219]
I would like to report an issue on the All tools and resources page at `/all_tools_and_resources`. Description of the issue:

I was looking at the list and I noticed that the `Beacon` bio.tools link a different tool than what is being described in the text and the other Tess and FAIRsharing links.

It is linking to https://bio.tools/beacon rather than https://bio.tools/ga4gh_beacon. But even the GA4GH Beacon entry on bio.tools is not very descriptive or useful in terms of linking to relevant documentation. The FAIRsharing entry is much better.

**Comment by bedroesb** [comment]
@mshadbolt Thanks for spotting this issue! I think linking to the correct beacon in bio.tools is a good first step. And indeed, we are aware that bio.tools is not always up to date/curated. That is why we do not populate our tables using info from bio.tools.

**Comment by bedroesb** [comment]
I think we will still link out to bio.tools out of completeness, since it is the correct ID. But lets hope the entry gets updated in the future.
