### ISSUE TITLE
Add DataPLAN to DMP

### ISSUE THREAD

**Issue by floradanna** [elixir-europe/rdmkit#1222]
**Link to the page of interest**
https://rdmkit.elixir-europe.org/data_management_plan
https://rdmkit.elixir-europe.org/data_management_plan#relevant-tools-and-resources

**Describe what you would change to the page**
Add DataPLAN.

The DataPLAN is a lightweight but easy to use tool. It has a flat learning curve and focuses on plant science research.
The tool can be reached here: https://plan.nfdi4plants.org/.

**List the tool(s)or resource(s) that are missing on the page (if applicable)**
- Name: DataPLAN
- Link: https://plan.nfdi4plants.org/.
- Description: DataPLAN is a FAIR and fast Data Management Plan (DMP) generator that focuses on plant science. The tool has a live-preview and is equipped with pre-written answers. DMPs can be generated in minutes by using DataPLAN.
- Registry (biotools or/and FAIRsharing ID) (optional)
- pages: data steward: researcher

https://nfdi4plants.org

Suggestion by @xiaoranzhou

**Comment by floradanna** [comment]
@xiaoranzhou 
- if the tool is developed by Germany for German institutes and projects, you could consider adding it to national page: https://rdmkit.elixir-europe.org/de_resources
- if the tool is specific for plants, it might be better to add it only in domain specific page about plants: https://rdmkit.elixir-europe.org/plant_sciences

**Comment by bedroesb** [comment]
small note, 
> tag it with "plant_sciences" domain page

the page ID for plant sciences is `plants`, to avoid/increase confusion :D

**Comment by xiaoranzhou** [comment]
> 

I think your suggestions make sense.
It can be put in the national page and also the "plants" page 😄

**Comment by sebeier** [comment]
> @wittigue please, add DataPLAN tool to the National page for Germany if you think it fits there (you can ask Xiaoran for further info).
> 
> @sebeier would it be ok if we tag DataPLAN with the domain page "plant sciences"? It seems a plant specific tool.
> 
> Since it is a plant specific tool done by German initiative and mainly used by initiatives within the country, I would suggest to have DataPLAN in the National page and tag it with "plant_sciences" domain page, but I would not keep it together with more "domain-agnostic" tools in the general DMP page.
> 
> What's your opinion?

Yes, fully agree. This should be linked Plants and the German National Page.

**Comment by xiaoranzhou** [comment]
Thanks a lot for the support and suggestions. 
This issue can be closed now.

**Comment by bedroesb** [comment]
:partying_face:
