### ISSUE TITLE
Add 4DN-BINA-OME-QUAREP (NBO-Q) Microscopy Metadata Specifications

### ISSUE THREAD

**Issue by strambc** [elixir-europe/rdmkit#1233]
**Link to the page of interest**
https://rdmkit.elixir-europe.org/bioimaging_data#metadata-collection

**Describe what you would change to the page**
Under Standard (meta)data formats/Solutions/Metadata, in addition to the OME-Data-Model and REMBI, the page currently lists "[Quality assessment working groups](https://quarep.org/)."

This is not correct. The initiative's name is **Quality Assessment and Reproducibility for Instruments and Images in Light Microscopy** and could be shortened as **Quality Assessment and Reproducibility in Light Microscopy** or **QUAREP-LiMi.**

Also, QUAREP-LiMi metadata WG has adopted and in partnership with manufacturers, is revising the 4D Nucleome (4DN) - BioImaging North America (BINA; https://www.bioimagingnorthamerica.org/qc-dm-wg/) - OME microscopy metadata specifications that were published in 2021.

So it would be great if the NBO-Q Microscopy Metadata Specifications could be listed explicitly on the page.

**List the tool(s)or resource(s) that are missing on the page (if applicable)**
- Name 
4DN-BINA-OME-QUAREP (NBO-Q) Microscopy Metadata Specifications

- Link 
https://www.nature.com/articles/s41592-021-01327-9 

- Description 
Rigorous record-keeping and quality control are required to ensure the quality, reproducibility and value of imaging data. The 4DN Initiative and BINA have published light Microscopy Metadata Specifications that extend the OME Data Model, scale with experimental intent and complexity, and make it possible for scientists to create comprehensive records of imaging experiments.
The Microscopy Metadata Specifications have been adopted by QUAREP-LiMi and are being revised in QUAREP-LiMi in collaboration with instrument manufacturers.

- Registry (biotools or/and FAIRsharing ID) (optional)

**Comment by jburel** [comment]
sure. Assign it to me

**Comment by jburel** [comment]
see https://github.com/elixir-europe/rdmkit/pull/1234

**Comment by korbinib** [comment]
closed by #1234

**Comment by bedroesb** [comment]
@strambc Thanks a lot for opening this issue and bringing this up! I hope #1234 solves you problem?

**Comment by jburel** [comment]
This is at the bottom of the page https://rdmkit.elixir-europe.org/bioimaging_data under ``Relevant tools and resources``

**Comment by strambc** [comment]
Thank you!
I had not seen it. Sorry about that.

One last thing, could you please correct the citation: 
from 
"[DN-BINA-OME-QUAREP (NBO-Q) Microscopy Metadata Specifications](https://www.nature.com/articles/s41592-021-01327-9) 

to 
"4DN-BINA-OME-QUAREP (NBO-Q) Microscopy Metadata Specifications"

Thanks a million!!!

**Comment by jburel** [comment]
PR to fix the issue https://github.com/elixir-europe/rdmkit/pull/1237
