### ISSUE TITLE
National Page for Ireland

### ISSUE THREAD

**Issue by Nazeeefa** [elixir-europe/rdmkit#1247]
**What topic do you wish to add?**
National resources page for Ireland (#1248) 

**Are there existing pages in the RDMkit website related to the requested page?**

**Resources**
If there are there resources that could be utilised for writing the new page, please list them below:
https://docs.google.com/document/d/17JnIvKdQ7WZhRu1QMhIrnBXyzZvR7nxFbsKGlQRAafc/edit#

**Context**
RDMkit Contentathon May 2023

**Comment by bedroesb** [comment]
This page is put online!
