### ISSUE TITLE
Pages on compliance

### ISSUE THREAD

**Issue by vildead** [elixir-europe/rdmkit#1270]
Currently we have compliance content split in few pages:
- [Human data](https://github.com/elixir-europe/rdmkit/blob/master/pages/your_domain/human_data.md)
- [Compliance monitoring](https://github.com/elixir-europe/rdmkit/blob/master/pages/your_tasks/compliance_monitoring.md)
- [GDPR compliance](https://github.com/elixir-europe/rdmkit/pull/1264) (proposed in PR)

and standing issue on ethics (https://github.com/elixir-europe/rdmkit/issues/616)

**Comment by froggypaule** [comment]
For Compliance monitoring, see also #1124 ; #616 has been replaced by #1275.
