### ISSUE TITLE
Page for Best Practices for FAIR AI/ML

### ISSUE THREAD

**Issue by smza** [elixir-europe/rdmkit#1273]
The content for for the FAIR AI/ML [page](https://docs.google.com/document/d/1B0kEmyQiylQ_r2fxyidFS4rjdxySvk9GR2b2cTIZufU/edit#heading=h.8ffr1z3a4ddw) has been initiated and is a work in progress. Once the page is in its final stage we'll move it to GitHub.

Tagging all the contributors
@F0nz0 @sfragkoul @uladzislau21 @jburel @mvaradi @parkyed @fpsom

Cheers,
Munazah

**What topic do you wish to add?**
Please provide a brief description.

**Are there existing pages in the RDMkit website related to the requested page?**

**Resources**
If there are there resources that could be utilised for writing the new page, please list them below:

**Context**
If this request is coming from a particular project, domain, or use-case please list them below:

**Comment by bedroesb** [comment]
Hello, everyone, I was wondering what the progress is of this page @F0nz0 @sfragkoul @uladzislau21 @jburel @mvaradi @parkyed @fpsom ? It would be nice to move to GitHub so we can start the review!

**Comment by sfragkoul** [comment]
Hey there! 
The document has been cleaned and ready from our side.
If there is nothing else requested, I think it is ready for review :)

**Comment by bedroesb** [comment]
@sfragkoul that is great! @DanFaria @pinarpink @bianchini88 @lauportell Would one of you have time to convert the google doc to markdown and move the tools to the new system?

**Comment by bedroesb** [comment]
or @sfragkoul if you would be up for a challenge, we off course would be happy to welcome this content in a pull request on this repo, following our contribution guidelines: https://bedroesb.github.io/rdmkit/github_way but one of the editors will first have to make the file for this

**Comment by smza** [comment]
> @sfragkoul that is great! @DanFaria @pinarpink @bianchini88 @lauportell Would one of you have time to convert the google doc to markdown and move the tools to the new system?

Hi @bedroesb, if @sfragkoul is not up for the challenge, I guess I should be doing since I was the editor responsible for this :)

**Comment by sfragkoul** [comment]
Hi @smza! As this is the start of the academic year (always a hectic period), combined also with a proposal deadline coming fast (Sep 28th), it would be great if I could take you up on your offer. Alternatively, if it's not too late, I can try picking this up after (i.e. mid October).

**Comment by smza** [comment]
> Hi @smza! As this is the start of the academic year (always a hectic period), combined also with a proposal deadline coming fast (Sep 28th), it would be great if I could take you up on your offer. Alternatively, if it's not too late, I can try picking this up after (i.e. mid October).

Hi @sfragkoul, I'll take care of this and ping you if I have any issues/comments regarding the content or the structure

**Comment by sfragkoul** [comment]
@smza Thank you! Of course, feel free to ask me if any issues come up :)

**Comment by bedroesb** [comment]
@smza and @sfragkoul As another editor pointed out, it might be best to make a Your Task and a Domain page out of this!

**Comment by smza** [comment]
@bedroesb do you mean that we have 2 pages under different section (Task and Domain) for the same topic?

**Comment by bedroesb** [comment]
@bianchini88 Could you give more detail to your proposal? We off course have to prevent duplication of content in two places.

**Comment by bianchini88** [comment]
Hi @bedroesb and @smza, I did not go through the document thoroughly (I am fighting deadlines this week), but at a superficial glance, it seems like sections 1 and 2 are very general and should indeed form a domain page, while 3 and 4 seem to describe specific tasks within.

**Comment by smza** [comment]
@sfragkoul @bianchini88 I've reviewed the document and I've left a few comments that need to be addressed. Section 1 & 4  for e.g. is not really a part of data management per se. Not sure if this is relevant from RDMkit POV. @bianchini88 could you please give you opinion?
@sfragkoul if you have other opinions maybe we can have a shot call after @bianchini88 has reviewed this.

**Comment by sfragkoul** [comment]
hey  @smza, thank you so much for your comments. I have answered most of them, please revisit to see whether it sheds more light  :) 

About the question regarding the suitability of  Section 1 & 4, I think they do fit in the whole picture, it really depends on how one would look at it. But it definitely is part of the best practices for open and FAIR ML/AI  methods.

I would be happy to have a call to discuss whatever might come up :)

**Comment by smza** [comment]
Thanks @sfragkou for the prompt response and addressing some of the comments. 
I understand from your POV why including sections 1 & 4 make a complete picture, however we also have to to view it  from RDMkit scope POV. 
I would wait for @bianchini88 comments and we can have a discussion after that. 

Cheers :)

**Comment by bianchini88** [comment]
Hi @smza and @sfragkoul. I went through the document and left a number of comments. While the page is extremely interesting to read and very rich in information, there is no clear focus on research data management, which makes it unsuitable for publication on RDMkit at the current stage. As opposed to other cases, this page is more challenging to write as it requires considerations on both data management and software management, the latter being a topic that is not extensively treated in RDMkit. This is the perfect occasion to expand on this. 

 I would suggest breaking down what I consider the core of the domain page (i.e. chapter 2) into smaller chunks and providing some examples. The correlation between considerations and solutions should also be improved. The first chapter should be shorter and more to the point, while the third one could become a "your task" page. 

As @smza suggested, we should have a short meeting at some point to agree on a suitable strategy.

**Comment by fpsom** [comment]
Hi all! Many thanks @bianchini88 @smza for your constructive feedback and comments! I attempted to address a few in the gdoc, and I also wanted to provide my two-cents in this thread here.

I fully agree that the connection between the current content of the page and RDM is not clearly evident - at the same time, this might be due to the fact that the subject "Best Practices for FAIR AI/ML" is rather broad by definition. As already mentioned a few times (both in the gdoc and in this thread), the ML process includes data, software, workflows, and other objects - and the current text attempted to reflect that. However, if keeping only a section or two helps clarify the message, it makes absolute sense to me.

Also, it may be worth noting that the discussion about the definition of FAIR for Machine Learning has already started in the context of RDA (https://www.rd-alliance.org/groups/fair-machine-learning-fair4ml-ig). Although we started this effort more than a year ago, we are still struggling as a community to identify which aspects of the ML lifecycle we need to focus on when discussing FAIR (much less come forward with particular definitions and examples). Hopefully we'll have some more progress during the upcoming plenary and the hackathon, so we can (hopefully) improve this text after as well. :)

In any case, I think that having a short TC might be useful and more efficient to push this forward and clarify any issues.

**Comment by bianchini88** [comment]
Hi @fpsom @sfragkoul @smza 
We all seem to agree it would be a good idea to have a short meeting about this. How do you suggest finding a suitable time slot? I could, for example, create a Doodle poll and share it here. Please let me know if you prefer other options.

**Comment by fpsom** [comment]
I think a doodle poll with some options for the next couple of weeks might be the most convenient and inclusive for anyone else in the drafting team that might want to join :). But that's just me; I'm absolutely fine with any other option/approach.

**Comment by sfragkoul** [comment]
@bianchini88  a doodle would be fine with me as well.

**Comment by bianchini88** [comment]
@fpsom @sfragkoul @smza 
I created a [Doodle poll](https://doodle.com/meeting/organize/id/egkYMWje).
Unfortunately, they reduced the amounts of options for free accounts, 
but, hopefully, we will manage to find a suitable time slot. All the other authors of the page are also invited @F0nz0 @uladzislau21 @jburel @mvaradi @parkyed.

**Comment by bianchini88** [comment]
@fpsom @sfragkoul @uladzislau21 Thank you for filling in the poll. 
I am unfortunately no longer available this Thursday, but Monday next week at 11:00 CEST is definitely a good option. Does it work for you, @smza?

**Comment by smza** [comment]
Hi Frederico @bianchini88 ,

I can do Monday 11:00, but I can join at 11:30 if that works.

**Comment by bianchini88** [comment]
Hi again @fpsom @sfragkoul @uladzislau21 @smza 

I got another response on the Doodle, and now it seems like Wednesday 11th October could be a better option. Would that work? 

Adriano, I am assuming you are @F0nz0, but please let me know if I am mistaken.

**Comment by uladzislau21** [comment]
Hi everyone!

For me Wednesday 11 am works.

Best,
Uladzislau
________________________________

**Comment by fpsom** [comment]
Hi all! Both me and @sfragkoul are running a session next week that is probably around that time, but in all likelihood this should be fine (we will know for sure by noon tomorrow if there is a conflict, and will post here - sorry for the inconvenience).

**Comment by fpsom** [comment]
Hi all, just a quick update: me and @sfragkoul are also fine for Wed, Oct 11th at 11:00 CEST (the session we are running is just before that, so - in case we run a bit overtime - we might be 5' late)

**Comment by smza** [comment]
> Hi @fpsom, thank you for letting us know.
> 
> @smza, will this work for you?

yes this works.

cheers

**Comment by bianchini88** [comment]
@fpsom @uladzislau21 @sfragkoul  @F0nz0

Perfect! We have a time slot. I intend to send a calendar invite, but I do not have the email address of you all. May I suggest you fill in the [CONTRIBUTORS file](https://github.com/elixir-europe/rdmkit/blob/master/_data/CONTRIBUTORS.yaml) with your details? In this way, I would get your email and we will add you to the contributors list in one single step. Alternatively, send me a message at fredebi@uio.no (but be aware you will have to fill your details in the yaml file at a later stage).

**Comment by uladzislau21** [comment]
I updated contributors file with my data.
Anyway, my email is uladzislau.vadadokhau@med.unideb.hu
See you all on the meeting :)

**Comment by sfragkoul** [comment]
Hey @uladzislau21, I just made a pull request after adding our data (mine and Fotis as well) in the contributors file :)

**Comment by bianchini88** [comment]
Dear All @smza @sfragkoul @fpsom @uladzislau21 
I have sent the calendar invite. Please let me know of any issues (e.g. with time zones).
