### ISSUE TITLE
Your Roles Pages

### ISSUE THREAD

**Issue by MijkeJetten** [elixir-europe/rdmkit#1276]
**Link to the page of interest**
https://rdmkit.elixir-europe.org/your_role

**Describe what you would change to the page**
During the Ghent Contenthaton, we have been working on updates for the Your Roles pages, via this [Google Doc](https://docs.google.com/document/d/1NavSc77LsX4dSa7WrVF2TNCoNuL9byd3uviOJOZStGg/edit#). Some is still work in progress, but since we propose structural adjustments (headers, adding roles), it would be useful to see if the editorial agrees with the proposals in a broad sense. Happy to take along any suggestions, before we finalise, adjust with Markdown and submit.    

Contactpersons are me and Ulrike W.

**List the tool(s)or resource(s) that are missing on the page (if applicable)**
Not applicable

**Comment by MijkeJetten** [comment]
To be discussed: add images for each page. We need help/suggestions for this to make sure it is not too much

**Comment by MijkeJetten** [comment]
Ant thoughts by the editorial board before we publish a first page?

**Comment by martin-nc** [comment]
FWIW I think they look good, and certainly better than what is there now. I'd say we go ahead and update the current pages/create the new ones. @wittigue what do you think?

**Comment by MijkeJetten** [comment]
Ok with both new pages, looks good. One thing: shouldn't we update the contributors list as well to (alone) the Ghent Your Role authors?

Let's prep the other pages that are good to go as well --> PI & data steward. Can you help @wittigue @martin-nc?

**Comment by MijkeJetten** [comment]
+ can we have a joint hour to finish the It & Trainer together, the three of us. ASAP if you are available @martin-nc @wittigue
