### ISSUE TITLE
Update the link

### ISSUE THREAD

**Issue by marikapop** [elixir-europe/rdmkit#1289]
**Link to the page of interest**
https://rdmkit.elixir-europe.org/machine_actionability

**Describe what you would change to the page**
Contains the link to RDA curated list of Life Sciences metadata standards in the text "Metadata schemas and checklists can be found within [RDA curated list of Life Sciences metadata standards](https://rd-alliance.github.io/metadata-directory/subjects/life-sciences.html) or among standards in [Fairsharing.org](https://fairsharing.org/standards/)."
This link going to no longer maintained page. 

The correct link is https://rdamsc.bath.ac.uk/

**Comment by bedroesb** [comment]
Thanks a lot @marikapop! @elixir-europe/rdmkit-editors can some of you have a look at this?
