### ISSUE TITLE
OMERO: tools not mentioned in in text

### ISSUE THREAD

**Issue by bedroesb** [elixir-europe/rdmkit#1297]
### Page: [OMERO](https://rdmkit.elixir-europe.org/omero_assembly)

In pull request #1249, we are implementing changes to how we handle tools, resulting in different rules for rendering the tools table at the bottom of pages. Going forward, only tools referenced in the text will be included in the bottom table of the page. Some of the tools have been tagged with the page_id of this page, and we are currently exploring how to incorporate these tools into the text.

**Tools that are not mentioned in the text:**
- [x] **[4DN-BINA-OME-QUAREP (NBO-Q) Microscopy Metadata Specifications](https://www.nature.com/articles/s41592-021-01327-9 )** - Rigorous record-keeping and quality control are required to ensure the quality, reproducibility and value of imaging data. The 4DN Initiative and BINA have published light Microscopy Metadata Specifications that extend the OME Data Model, scale with experimental intent and complexity, and make it possible for scientists to create comprehensive records of imaging experiments. The Microscopy Metadata Specifications have been adopted by QUAREP-LiMi and are being revised in QUAREP-LiMi in collaboration with instrument manufacturers

Would you kindly review these tools and determine if they should be mentioned (as a link) in the text? If necessary, please propose changes to the text through a pull request on this temporary [instance of the RDMkit](https://bedroesb.github.io/rdmkit) by clicking on the pencil icon next to the title and following the instructions in this [guide](https://bedroesb.github.io/rdmkit/tool_resource_update). @jburel

**Comment by bedroesb** [comment]
We will move to the new system in the week of the 24th of Juli, so please make sure changes are comments are made before this date. Thanks a lot in advance!

**Comment by bedroesb** [comment]
@jburel any opinions on this one? :)

**Comment by jburel** [comment]
@bedroesb Catching up with things. I have been travelling to various meetings.
We should be able to integrate links in text.

**Comment by jburel** [comment]
Apologies I forgot to update. 
I will do it today against your account @bedroesb

**Comment by bedroesb** [comment]
No apologies needed! I will be on the lookout!

**Comment by bedroesb** [comment]
Done in https://github.com/bedroesb/rdmkit/pull/48 thanks @jburel
