### ISSUE TITLE
Data analysis: tools not mentioned in in text

### ISSUE THREAD

**Issue by bedroesb** [elixir-europe/rdmkit#1299]
### Page: [Data analysis](https://rdmkit.elixir-europe.org/data_analysis)

In pull request #1249, we are implementing changes to how we handle tools, resulting in different rules for rendering the tools table at the bottom of pages. Going forward, only tools referenced in the text will be included in the bottom table of the page. Some of the tools have been tagged with the page_id of this page, and we are currently exploring how to incorporate these tools into the text.

**Tools that are not mentioned in the text:**
- ~**[Ada Discovery Analytics (Ada)](https://ada-discovery.github.io/)** - Ada is a performant and highly configurable system for secured integration, visualization, and collaborative analysis of heterogeneous data sets, primarily targeting clinical and experimental sources.~ _No real lading page, latest commit 2 years ago, still in development?_
- [x] **[BIAFLOWS](https://biaflows.neubias.org/)** - BIAFLOWS is an open-soure web framework to reproducibly deploy and benchmark bioimage analysis workflows
- ~**[BIII](https://biii.eu/)** - The BioImage Informatics Index is a registry of software tools, image databases for benchmarking, and training materials for bioimage analysis~ - https://github.com/bedroesb/rdmkit/pull/62
- ~**[CalibraCurve](https://github.com/mpc-bioinformatics/CalibraCurve)** - A highly useful and flexible tool for calibration of targeted MS?based measurements. CalibraCurve enables an automated batch-mode determination of dynamic linear ranges and quantification limits for both targeted proteomics and similar assays. The software uses a variety of measures to assess the accuracy of the calibration and provides intuitive visualizations.~ _Specific analysis tool, does not fit the narrative of this page and is also not helpful_
- ~**[GENEID](https://genome.crg.cat/software/geneid/index.html)** - Geneid is an ab initio gene finding program used to predict genes along DNA sequences in a large set of organisms.~ _This is not a data management related data analysis tool, but an outdated gene prediction tool from 2005_
- ~**[GRAPE 2.0](https://github.com/guigolab/grape-nf)** - The GRAPE pipeline provides an extensive pipeline for RNA-Seq analyses. It allows the creation of an automated and integrated workflow to manage, analyse and visualize RNA-Seq data.~ _Specific workflow, does not fit the narrative of this page and is also not helpfull_
- ~**[HumanMine](https://www.humanmine.org/)** - HumanMine integrates many types of human data and provides a powerful query engine, export for results, analysis for lists of data and FAIR access via web services.~ _Added to other pages, does not fit the current subsections of this page_
- ~**[iCloud](https://www.icloud.com/)** - Data sharing~ _ICloud is not meant for research purposes_
- [x] **[LUMI](https://www.lumi-supercomputer.eu/)** - EuroHPC world-class supercomputer
- [x] **[OpenStack](https://www.openstack.org/)** - OpenStack is an open source cloud computing infrastructure software project and is one of the three most active open source projects in the world
- ~**[OTP](https://gitlab.com/one-touch-pipeline/otp)** - One Touch Pipeline (OTP) is a data management platform for running bioinformatics pipelines in a high-throughput setting, and for organising the resulting data and metadata.~ _Poor quality [documentation](https://one-touch-pipeline.gitlab.io/otp/) -> not clear how you can use it_
- ~**[PAA](https://bioconductor.org/packages/PAA/)** - PAA is an R/Bioconductor tool for protein microarray data analysis aimed at biomarker discovery.~ _Added to other pages, does not fit the current subsections of this page_
- ~**[PIA - Protein Inference Algorithms](https://github.com/mpc-bioinformatics/pia)** - PIA is a toolbox for mass spectrometrey based protein inference and identification analysis.~ _Added to other pages, does not fit the current subsections of this page_
- ~**[Reva](https://reva.link/)** - Reva connects cloud storages and application providers~ _Added to other pages, does not fit the current subsections of this page_
- ~**[Rucio](https://rucio.cern.ch/)** - Rucio - Scientific Data Management~ _Added to other pages, does not fit the current subsections of this page_
- ~**[ScienceMesh](https://sciencemesh.io/)** - ScienceMesh - frictionless scientific collaboration and access to research services~ - _Added to other pages, does not fit the current subsections of this page_
- ~**[Semares](https://www.genevention.com/products)** - All-in-one platform for life science data management, semantic data integration, data analysis and visualization~ - _Added to other pages, does not fit the current subsections of this page_
- ~**[tranSMART](https://github.com/transmart)** - Knowledge management and high-content analysis platform enabling analysis of integrated data for the purposes of hypothesis generation, hypothesis validation, and cohort discovery in translational research.~ - _Added to other pages, does not fit the current subsections of this page_
- ~**[TXG-MAPr](https://txg-mapr.eu/)** - A tool that contains weighted gene co-expression networks obtained from the Primary Human Hepatocytes, rat kidney, and liver TG-GATEs dataset.~ - _Added to other pages, does not fit the current subsections of this page_

Would you kindly review these tools and determine if they should be mentioned (as a link) in the text? If necessary, please propose changes to the text through a pull request on this temporary [instance of the RDMkit](https://bedroesb.github.io/rdmkit) by clicking on the pencil icon next to the title and following the instructions in this [guide](https://bedroesb.github.io/rdmkit/tool_resource_update). @OlivierCollin, @stain, @mr-c, @svedziok

**Comment by bedroesb** [comment]
We will move to the new system in the week of the 24th of Juli, so please make sure changes are comments are made before this date. Thanks a lot in advance!

**Comment by svedziok** [comment]
I added a bullet point about OpenStack. OTP can be removed as it to specific; guess that is similar to other tools in this list

**Comment by bedroesb** [comment]
And went over all the tools and most of them were already added to a page where they fit better. Some other ones where irrelevant. The ones I could find a place for where added here https://github.com/bedroesb/rdmkit/pull/63
