### ISSUE TITLE
Intrinsically disordered proteins: tools not mentioned in in text

### ISSUE THREAD

**Issue by bedroesb** [elixir-europe/rdmkit#1302]
### Page: [Intrinsically disordered proteins](https://rdmkit.elixir-europe.org/intrinsically_disordered_proteins)

In pull request #1249, we are implementing changes to how we handle tools, resulting in different rules for rendering the tools table at the bottom of pages. Going forward, only tools referenced in the text will be included in the bottom table of the page. Some of the tools have been tagged with the page_id of this page, and we are currently exploring how to incorporate these tools into the text.

**Tools that are not mentioned in the text:**
- [x] **[APID Interactomes](http://apid.dep.usal.es/)** - APID (Agile Protein Interactomes DataServer) is a server that provides a comprehensive collection of protein interactomes for more than 400 organisms based in the integration of known experimentally validated protein-protein physical interactions (PPIs)
- [x] **[SASBDB](https://www.sasbdb.org/)** - Small Angle Scattering Biological Data Bank

Would you kindly review these tools and determine if they should be mentioned (as a link) in the text? If necessary, please propose changes to the text through a pull request on this temporary [instance of the RDMkit](https://bedroesb.github.io/rdmkit) by clicking on the pencil icon next to the title and following the instructions in this [guide](https://bedroesb.github.io/rdmkit/tool_resource_update). @ivanmicetic

**Comment by bedroesb** [comment]
We will move to the new system in the week of the 24th of Juli, so please make sure changes are comments are made before this date. Thanks a lot in advance!

**Comment by ivanmicetic** [comment]
Hi,
the resource SASBDB is a primary deposition community database and is mentioned in the text under "Annotating or curating.../Solutions" so it should be present in the list of tools. However I don't know who added APID Interactome so I'll remove it from `tool_and_resource_list.yml`.

**Comment by bedroesb** [comment]
@ivanmicetic thanks for the feedback, could you link me the line to where SASBDB is mentioned? https://github.com/elixir-europe/rdmkit/blob/master/pages/your_domain/intrinsically_disordered_proteins.md?plain=1 I can not find it in the paragraph you mention.

**Comment by ivanmicetic** [comment]
> @ivanmicetic thanks for the feedback, could you link me the line to where SASBDB is mentioned? https://github.com/elixir-europe/rdmkit/blob/master/pages/your_domain/intrinsically_disordered_proteins.md?plain=1 I can not find it in the paragraph you mention.

Hi Bert, it's mentioned in line 35 [here](https://github.com/elixir-europe/rdmkit/blob/master/pages/your_domain/intrinsically_disordered_proteins.md?plain=1#L35).

**Comment by bedroesb** [comment]
@ivanmicetic for some mysterious reason it got lost in the development branch, I added it back from the current RDMkit IDP page, thanks!

**Comment by bedroesb** [comment]
Both tools are added to the page.
