### ISSUE TITLE
Existing data: tools not mentioned in in text

### ISSUE THREAD

**Issue by bedroesb** [elixir-europe/rdmkit#1304]
### Page: [Existing data](https://rdmkit.elixir-europe.org/existing_data)

In pull request #1249, we are implementing changes to how we handle tools, resulting in different rules for rendering the tools table at the bottom of pages. Going forward, only tools referenced in the text will be included in the bottom table of the page. Some of the tools have been tagged with the page_id of this page, and we are currently exploring how to incorporate these tools into the text.

**Tools that are not mentioned in the text:**
- ~**[BASE](https://www.base-search.net/)** - A search engine for academic web resources~
- [x] **[ELIXIR Core Data Resources](https://elixir-europe.org/platforms/data/core-data-resources)** - Set of European data resources of fundamental importance to the wider life-science community and the long-term preservation of biological data
- [x] **[Evidence and Conclusion Ontology (ECO)](https://evidenceontology.org/)** - Controlled vocabulary that describes types of evidence and assertion methods
- [x] **[OpenAIRE Explore](https://explore.openaire.eu/search/find)** - Explore Open Access research outcomes from OpenAIRE network

Would you kindly review these tools and determine if they should be mentioned (as a link) in the text? If necessary, please propose changes to the text through a pull request on this temporary [instance of the RDMkit](https://bedroesb.github.io/rdmkit) by clicking on the pencil icon next to the title and following the instructions in this [guide](https://bedroesb.github.io/rdmkit/tool_resource_update). @rwwh, @floradanna, @pinarpink, @yvonnekallberg, @KarelBerka, @marko-whatever, @OlivierCollin, @wittigue

**Comment by bedroesb** [comment]
We will move to the new system in the week of the 24th of Juli, so please make sure changes are comments are made before this date. Thanks a lot in advance!

**Comment by YvonneKallberg** [comment]
I've added the ELIXIR core resources and ECO in a [PR](https://github.com/bedroesb/rdmkit/pull/39), but have no opinion on the other tools.

**Comment by wittigue** [comment]
I would suggest to delete "[BASE](https://www.base-search.net/) - A search engine for academic web resources" from this page because it's focusing on document/literature search. Otherwise we also have to mention EuropePMC or PubMed.

**Comment by bedroesb** [comment]
All tools have been solved on this page!
