### ISSUE TITLE
Biomolecular simulation data: tools not mentioned in in text

### ISSUE THREAD

**Issue by bedroesb** [elixir-europe/rdmkit#1305]
### Page: [Biomolecular simulation data](https://rdmkit.elixir-europe.org/biomolecular_simulation_data)

In pull request #1249, we are implementing changes to how we handle tools, resulting in different rules for rendering the tools table at the bottom of pages. Going forward, only tools referenced in the text will be included in the bottom table of the page. Some of the tools have been tagged with the page_id of this page, and we are currently exploring how to incorporate these tools into the text.

**Tools that are not mentioned in the text:**
- [x] **[Bioactive Conformational Ensemble](https://mmb.irbbarcelona.org/BCE/)** - Platform designed to efficiently generate bioactive conformers and speed up the drug discovery process.
- [x] **[BioExcel COVID-19](https://bioexcel-cv19.bsc.es/#/)** - Platform designed to provide web-access to atomistic-MD trajectories for macromolecules involved in the COVID-19 disease.
- [x] **[COVID-19 Molecular Structure and Therapeutics Hub](https://covid.bioexcel.eu/)** - COVID-19 Molecular Structure and Therapeutics Hub
- [ ] **[Mendeley data](https://data.mendeley.com/)** - Multidisciplinary, free-to-use open repository specialized for research data
- [x] **[MoDEL Covid19](https://bioexcel-cv19.bsc.es/#/)** - Database of COVID-19 related atomistic Molecular Dynamic Trajectories

Would you kindly review these tools and determine if they should be mentioned (as a link) in the text? If necessary, please propose changes to the text through a pull request on this temporary [instance of the RDMkit](https://bedroesb.github.io/rdmkit) by clicking on the pencil icon next to the title and following the instructions in this [guide](https://bedroesb.github.io/rdmkit/tool_resource_update). @KarelBerka, @adamhospital

**Comment by adamhospital** [comment]
Hi Bert,

maybe I don't understand the question, but these tools are all mentioned in the text (see attached image). 

Should we add something else? 

-Adam-


<img width="833" alt="image" src="https://github.com/elixir-europe/rdmkit/assets/15168928/67cc2ea7-5397-4e12-807e-303832ab7a56">

**Comment by bedroesb** [comment]
We will move to the new system in the week of the 24th of Juli, so please make sure changes are comments are made before this date. Thanks a lot in advance!

**Comment by bedroesb** [comment]
@adamhospital thanks a lot for the quick repsonse, let me quickly have a look how this could happen. (these issues were created automatically)

**Comment by bedroesb** [comment]
@adamhospital `COVID-19 Molecular Structure and Therapeutics Hub` or `MolSSI - BioExcel COVID-19 therapeutics hub`  are both being used, which one do we prefer?

**Comment by adamhospital** [comment]
Hi Bert, the second one (`MolSSI - BioExcel COVID-19 therapeutics hub`) is better. 
Thanks!

-Adam-

**Comment by bedroesb** [comment]
last question @adamhospital, dou you think [Mendeley data](https://data.mendeley.com/) should be linked on this page?

**Comment by adamhospital** [comment]
If I'm not wrong, I think @KarelBerka suggested to add Mendeley data. What do you think Karel?

**Comment by KarelBerka** [comment]
I do not think it is needed to be added.
