### ISSUE TITLE
Data organisation: tools not mentioned in in text

### ISSUE THREAD

**Issue by bedroesb** [elixir-europe/rdmkit#1312]
### Page: [Data organisation](https://rdmkit.elixir-europe.org/data_organisation)

In pull request #1249, we are implementing changes to how we handle tools, resulting in different rules for rendering the tools table at the bottom of pages. Going forward, only tools referenced in the text will be included in the bottom table of the page. Some of the tools have been tagged with the page_id of this page, and we are currently exploring how to incorporate these tools into the text.

**Tools that are not mentioned in the text:**
- [x] **[Cookiecutter](https://github.com/cookiecutter/cookiecutter)** - A command-line utility that creates projects from cookiecutters (project templates), e.g. creating a Python package project from a Python package project template.
- [x] **[GitLab](https://gitlab.com/gitlab-org/gitlab)** - GitLab is an open source end-to-end software development platform with built-in version control, issue tracking, code review, CI/CD, and more. Self-host GitLab on your own servers, in a container, or on a cloud provider.
- [ ] ~**[HumanMine](https://www.humanmine.org/)** - HumanMine integrates many types of human data and provides a powerful query engine, export for results, analysis for lists of data and FAIR access via web services.~
- [ ] ~**[SMASCH](https://smasch.pages.uni.lu)** - SMASCH (Smart Scheduling) system, is a web-based tooldesigned for longitudinal clinical studies requiring recurrent follow-upvisits of the participants. SMASCH controls and simplifies the scheduling of big database of patients. Smasch is also used to organize the daily plannings (delegation of tasks) for the different medical professionals such as doctors, nurses and neuropsychologists.~

Would you kindly review these tools and determine if they should be mentioned (as a link) in the text? If necessary, please propose changes to the text through a pull request on this temporary [instance of the RDMkit](https://bedroesb.github.io/rdmkit) by clicking on the pencil icon next to the title and following the instructions in this [guide](https://bedroesb.github.io/rdmkit/tool_resource_update). @siirif, @minnami, @yvonnekallberg, @ivanmicetic, @naeemmuhammad

**Comment by bedroesb** [comment]
We will move to the new system in the week of the 24th of Juli, so please make sure changes are comments are made before this date. Thanks a lot in advance!

**Comment by floradanna** [comment]
[HumanMine](https://www.humanmine.org/) is already mentioned on the Human data page, where it fits best.
[SMASCH](https://smasch.pages.uni.lu/) is already mentioned on the TransMed page, where it fits best.

**Comment by bedroesb** [comment]
:ok_hand:
