### ISSUE TITLE
Plant sciences: tools not mentioned in in text

### ISSUE THREAD

**Issue by bedroesb** [elixir-europe/rdmkit#1313]
### Page: [Plant sciences](https://rdmkit.elixir-europe.org/plant_sciences)

In pull request #1249, we are implementing changes to how we handle tools, resulting in different rules for rendering the tools table at the bottom of pages. Going forward, only tools referenced in the text will be included in the bottom table of the page. Some of the tools have been tagged with the page_id of this page, and we are currently exploring how to incorporate these tools into the text.

**Tools that are not mentioned in the text:**
- [x] **[Data INRAE](https://data.inrae.fr/)** - Dataverse for life sciences and agronomic related data
- [x] **[GnpIS](https://urgi.versailles.inrae.fr/gnpis/)** - A multispecies integrative information system dedicated to plant and fungi pests. It allows researchers to access genetic, phenotypic and genomic data. It is used by both large international projects and the French National Research Institute for Agriculture, Food and Environment.

Would you kindly review these tools and determine if they should be mentioned (as a link) in the text? If necessary, please propose changes to the text through a pull request on this temporary [instance of the RDMkit](https://bedroesb.github.io/rdmkit) by clicking on the pencil icon next to the title and following the instructions in this [guide](https://bedroesb.github.io/rdmkit/tool_resource_update). @afablondon, @sebeier, @cpommier, @erlefloch, @DanFaria

**Comment by bedroesb** [comment]
We will move to the new system in the week of the 24th of Juli, so please make sure changes are comments are made before this date. Thanks a lot in advance!

**Comment by erlefloch** [comment]
Hi @bedroesb , Data INRAE is deprecated. The new dataverse is Recherche Data Gouv. We have updated all the pages and the tools and resources google sheet.

**Comment by erlefloch** [comment]
And GNPIS can be removed as it is just one BRAPI compliant repo among others.

**Comment by bedroesb** [comment]
@erlefloch would you be willing to update in the IFB page the mentions of Data INRAE to the new ones you mentioned? The tool to be added here: https://github.com/bedroesb/rdmkit/blob/demo/_data/tool_and_resource_list.yml and the mentions here: https://github.com/bedroesb/rdmkit/blob/demo/pages/tool_assembly/ifb_assembly.md?plain=1#L83

**Comment by bedroesb** [comment]
update: I see Data INRAE is also ragged under plant sciences, plant pheno and plant geno assembly, besides IFB. My request is bigger than I thought :D @erlefloch

**Comment by bedroesb** [comment]
Since [Data INRAE](https://data.inrae.fr/) is deprecated and taken out of the tools and resources list, this issue can be closed.
