### ISSUE TITLE
Data protection: tools not mentioned in in text

### ISSUE THREAD

**Issue by bedroesb** [elixir-europe/rdmkit#1316]
### Page: [Data protection](https://rdmkit.elixir-europe.org/data_protection)

In pull request #1249, we are implementing changes to how we handle tools, resulting in different rules for rendering the tools table at the bottom of pages. Going forward, only tools referenced in the text will be included in the bottom table of the page. Some of the tools have been tagged with the page_id of this page, and we are currently exploring how to incorporate these tools into the text.

**Tools that are not mentioned in the text:**
- [x] **[DPIA Knowledge Model](https://converge.ds-wizard.org/knowledge-models/elixir.lu:dpia-research:0.1.0)** - A DSW knowledge model guiding users through a set of questions to collect information necessary for a research project Data Protection Impact Assessment (DPIA).
- [x] **[ERPA](https://gitlab.sib.swiss/clinbio/erpa-app)** - Web-based tool allowing users to create and manage a register of personal data processing activities (ROPA).
- [x] **[EU General Data Protection Regulation](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R0679&from=EN)** - Regulation (eu) 2016/679 of the european parliament and of the council on the protection of natural persons with regard to the processing of personal data and on the free movement of such data, and repealing directive 95/46/ec (general data protection regulation).

Would you kindly review these tools and determine if they should be mentioned (as a link) in the text? If necessary, please propose changes to the text through a pull request on this temporary [instance of the RDMkit](https://bedroesb.github.io/rdmkit) by clicking on the pencil icon next to the title and following the instructions in this [guide](https://bedroesb.github.io/rdmkit/tool_resource_update). @pinarpink, @yvonnekallberg, @vildead, @nicjar

**Comment by bedroesb** [comment]
We will move to the new system in the week of the 24th of Juli, so please make sure changes are comments are made before this date. Thanks a lot in advance!

**Comment by vildead** [comment]
Dear @bedroesb , can it be included in the [Solutions](https://github.com/bedroesb/rdmkit/blob/demo/pages/your_tasks/data_protection.md#solution-1) section of the page? Or it has to be part of the main text? Or it doesn't matter?

**Comment by vildead** [comment]
> Dear @bedroesb , can it be included in the [Solutions](https://github.com/bedroesb/rdmkit/blob/demo/pages/your_tasks/data_protection.md#solution-1) section of the page? Or it has to be part of the main text? Or it doesn't matter?

not relevant anymore - see the proposed changes here: https://github.com/bedroesb/rdmkit/pull/42

**Comment by bedroesb** [comment]
@vildeadit can be with solutions for sure! This is for me also the main text :) Do we have something for [DPIA Knowledge Model](https://converge.ds-wizard.org/knowledge-models/elixir.lu:dpia-research:0.1.0)  or do we leave it out?

**Comment by vildead** [comment]
> @vildead it can be with solutions for sure! This is for me also the main text :) Do we have something for [DPIA Knowledge Model](https://converge.ds-wizard.org/knowledge-models/elixir.lu:dpia-research:0.1.0) or do we leave it out?

@bedroesb is this [line](https://github.com/bedroesb/rdmkit/blob/63db0cd4754277be4638054746f48560673d89be/pages/your_tasks/data_protection.md?plain=1#L121) not enough?

**Comment by bedroesb** [comment]
:see_no_evil: I am officially blind, ok thanks for adding!

**Comment by bedroesb** [comment]
Thanks!
