### ISSUE TITLE
faircookbook link description in the plant sciences page is not precise enough

### ISSUE THREAD

**Issue by erlefloch** [elixir-europe/rdmkit#1329]
Currently it is "Improving dataset maturity - the MIAPPE use case", which is not very clear.
![image](https://github.com/elixir-europe/rdmkit/assets/90708860/6cff7265-ff95-4a21-be4e-dd9cc8800eb8)

I propose to make a new description in this PR: https://github.com/FAIRplus/the-fair-cookbook/pull/595

@cpommier @sebeier

**Comment by bedroesb** [comment]
I agree with you, but as you mention, this is because the title in FCB is wrong, we sync automatically with the titles from FCB, so I think this issue here can be closed?

**Comment by erlefloch** [comment]
Yes if the sync is automatic it's perfect !
