### ISSUE TITLE
New page - How to draw a research data flow diagram

### ISSUE THREAD

**Issue by vildead** [elixir-europe/rdmkit#1382]
**What topic do you wish to add?**
IDEA: Having a basic data flow diagram already in planning phase of a project helps tremendously in general understanding of the project. For many starting researchers, drafting such diagram is not very easy or it ends up in very strange diagram focused more on science than data. 

Short guide with basic principles on how to design/draw such diagram could be introduced either under Planning data lifecycle phase page or (better) as new Task page.

**Are there existing pages in the RDMkit website related to the requested page?**
- Planning

**Comment by bedroesb** [comment]
@vildead great idea! Would you be willing to start the draft for such a page, or know somebody that could do this? :)

**Comment by vildead** [comment]
> @vildead great idea! Would you be willing to start the draft for such a page, or know somebody that could do this? :) 

Sure! I just wanted to know if RDMKit is the right place for such guide. I will include it in our training in October - first draft could be ready right after.

**Comment by bedroesb** [comment]
it off course depends on how detailed, because step by step procedures are done in FAIRCookbook, but describing the need and which tools you can use to do so fits here!

**Comment by vildead** [comment]
changes added in #1528

**Comment by vildead** [comment]
7 points on diagram drawing from one of our postdocs:

My 7 Principles of Better Dataflow Design (in health research)

- Human Presence: The presence of humans (including patients, clinicians, and researchers) is integral to the workflow, rendering the diagram action-role based.
- Established End Points: In a patient-centric study, the process should commence with the patient and culminate in an interaction or orientation for relevant individuals, be it clinicians, omics researchers, or policy makers.
- Principle of Objectivity: Each physical or virtual node must possess a clearly defined shape and color, with or without an accompanying icon.
- Uniformity and Distinction: Nodes of the same type should share identical shapes, while distinctions among node subtypes should be indicated through variations in border color and pattern (e.g., dotted or dashed).
- Segregation: Digital and physical flows should exhibit clear differentiation; for instance, a dashed arrow may represent physical movements, such as the transfer of biosamples to a biobank.
- Self-explaining: Diagram should be self sufficient to explain the thought-process behind it like any other fine-art
- Simplicity: Strive for minimalism by employing a limited variety of shapes and colors.
