### ISSUE TITLE
Announce the RDMkit Club on the RDMkit website

### ISSUE THREAD

**Issue by marikapop** [elixir-europe/rdmkit#1387]
Issue  #1377 already updated governance to post CONVERGE. However, advertising of RDMkit Club is missing. 

Discuss on RDMkit Club meeting:
- text;
- location.

**Comment by bedroesb** [comment]
What kind of advertisement are we thinking of and where would this go ? :)

**Comment by bedroesb** [comment]
Because we have to keep in mind our target audience, who will benefit from this information.

**Comment by marikapop** [comment]
That rise the question who is target audience of RDMkit Club? In the future, I assume, it would be more people than just CONVERGE WP3. How those people would find info about Club meetings? Word-of-mouth is good but info on website is better.

We can put meetings on Events page. Where to put general information I would discuss on meeting. One possible place is Community (page does not exist now).

**Comment by bedroesb** [comment]
> That rise the question who is target audience of RDMkit Club? In the future, I assume, it would be more people than just CONVERGE WP3.
My hope/assumption is that our target audience is every data steward/researcher etc in europe that want to manage their data. That is why I am not so keen on adding info on the landing page that is specific to our internal meetings /organisation. This is irrational to people that are consuming the info on our website.

I personally like the idea of making a community page!

**Comment by marikapop** [comment]
I am sorry for not being clear. I have never thought about landing page. Readers of RDMkit does not need that info. Meetings info is interested for people who would like to contribute to or improve RDMkit but who was not part of Converge.

**Comment by smza** [comment]
Reference for content: 
https://docs.google.com/document/d/1TW-sT_UEDi4KXODpXoOcTqsupoWfLc1sAM-F3XWkzuE/edit#heading=h.gjdgxs
