### ISSUE TITLE
Repeated text across two pages

### ISSUE THREAD

**Issue by martin-nc** [elixir-europe/rdmkit#1407]
The first section of the [Planning page](https://rdmkit.elixir-europe.org/planning) ("What is data management planning?") has some bullet points to consider for a DMP. These bullet points are repeated in the first section of the [Data Management Plan](https://rdmkit.elixir-europe.org/data_management_plan) page. Normally repeated content is a bad idea, so should we change the text in one of the pages?  Perhaps the bullet points in the Planning page could be removed, and replaced with a link to the DMP page for more details?
![Screenshot 2023-11-10 at 16 26 34](https://github.com/elixir-europe/rdmkit/assets/15261745/398d8a09-3204-49ab-a42e-3ab1feef9607)

**Comment by Nazeeefa** [comment]
> Perhaps the bullet points in the Planning page could be removed, and replaced with a link to the DMP page for more details?

Thanks @martin-nc! This makes sense to me.
For example, we could write _'See [Data Management Plan page](https://rdmkit.elixir-europe.org/data_management_plan) to understand common components to consider for a DMP'_ 
OR we could write/hyperlink "See what are the common components of DMP" after the sentence "Solutions regarding the handling of the data generated within a project is usually formalised in a Data Management Plan (DMP)".
