### ISSUE TITLE
Support Page: Institutions and Funders

### ISSUE THREAD

**Issue by Nazeeefa** [elixir-europe/rdmkit#1425]
**Link to the page of interest**
https://rdmkit.elixir-europe.org/support

**Describe what you would change to the page**
- Add University of Oslo logo to the page https://github.com/elixir-europe/rdmkit/blob/master/images/institutions/UiO_logo.svg
- Replace the old 'The Research Council of Norway' with new one, that can be found here https://identitet.forskningsradet.no/verktoykasse/logo#stoettet-av-forskningsraadet-merke

**List the tool(s)or resource(s) that are missing on the page (if applicable)**
N/A

**Comment by bedroesb** [comment]
I will be happy to review the pull request! Changes need to be made to _data/affiliations.yml
