### ISSUE TITLE
Additional policies from the research council on the Norwegian national page

### ISSUE THREAD

**Issue by bianchini88** [elixir-europe/rdmkit#1426]
**Link to the page of interest**
https://rdmkit.elixir-europe.org/no_resources#funder-policies-on-research-data

**Describe what you would change to the page**
Add these 
* https://www.forskningsradet.no/siteassets/forskningspolitisk-radgivning/apen-forskning/nfr-policy-open-science-eng.pdf
* https://www.forskningsradet.no/siteassets/forskningspolitisk-radgivning/apen-forskning/nfr-policy-apen-forskning-norsk-ny.pdf

**Comment by bianchini88** [comment]
Related: add recommendation for maDMP standard

**Comment by korbinib** [comment]
started a PR #1444 . Uncertain if there could be an improved way to reference national tools with id. - Happy for input @bedroesb

**Comment by bianchini88** [comment]
Thank you @korbinib. Regarding IDs and such, I would appreciate a system more in line with the rest of the website in terms of structure and syntax.
