### ISSUE TITLE
National pages miss page_id

### ISSUE THREAD

**Issue by korbinib** [elixir-europe/rdmkit#1450]
**Link to the page of interest**
https://rdmkit.elixir-europe.org/national_resources

**Describe what you would change to the page**
Adding page IDs to the national resources pages
Hence they are e.g. also not listed here: https://rdmkit.elixir-europe.org/website_overview

**Comment by bedroesb** [comment]
This was done on purpose because the page_id is only used to link towards pages, and we never link out to National resource pages using the page_id. I maybe should improve the include that the heading does not appear when no children are present

**Comment by bedroesb** [comment]
Because I agree, it looks odd now and was raised also in the IDTk
