### ISSUE TITLE
Metadata standard for single-cell experiments missing in domain page

### ISSUE THREAD

**Issue by bianchini88** [elixir-europe/rdmkit#1464]
**Link to the page of interest**
https://rdmkit.elixir-europe.org/single_cell_sequencing

**Describe what you would change to the page**
Point to the standard below in the [long-term-data-storage-and-accessibility](https://rdmkit.elixir-europe.org/single_cell_sequencing#long-term-data-storage-and-accessibility) section. Discussed with @korbinib. 

**List the tool(s)or resource(s) that are missing on the page (if applicable)**
- Name: miSCe
- Link: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9302581/
- Description: minimum information about a single-cell experiment supported by ArrayExpress

**Comment by bianchini88** [comment]
Note: the said standard is not present in FAIRsharing. @bianchini88 created an entry for it which is currently waiting for approval by the FAIRsharing curation group.

**Comment by bianchini88** [comment]
Update on the FAIRsharing entry: I somehow missed additional tabs requiring more metadata, so the entry is not approved in its current state and I will have to revise the submission. Due to deadlines, I do not expect I will be able to work on this before next week.

**Comment by johrollin** [comment]
I don't know if the requirement needed for GEO are the same than the one of ArraryExpress. 
The most complete document on required information seems to the the EBI/ArrayExpress the submissions page contain more complete and concrete information and is also maintained up-to date compared to the linked article (So maybe it is a better link ?): https://www.ebi.ac.uk/fg/annotare/help/what_to_submit.html
On the GEO part I didn't find anything precise, (apart for some external proposal like here: https://www.bioconductor.org/packages/devel/bioc/vignettes/clustifyr/inst/doc/geo-annotations.html).

Recommending the miSCe as described in the article seems a good idea, but it is centered mostly on ArrayExpress and I am not that confident the the meta-data table required for ArrayExpress  submission will work on GEO (It can be a way to try to push them to higher standart ?).

I don't know any other standard on required information for storage on SCe.

**Comment by johrollin** [comment]
Well, I will let you make the PR if it is ok. 
You can Tag me if there is new modifications idea to the page, I will happily discuss it if I am available at the time.

**Comment by bianchini88** [comment]
> Well, I will let you make the PR if it is ok.

Ok

>  You can Tag me if there is new modifications idea to the page, I will happily discuss it if I am available at the time.

I will do that, but keep in mind that anyone can contribute to the page and I will not necessarily be the reviewer every time.
