### ISSUE TITLE
command for git cloning the repository fails

### ISSUE THREAD

**Issue by bianchini88** [elixir-europe/rdmkit#1480]
**Link to the page of interest**
https://rdmkit.elixir-europe.org/working_with_git#forking---branching---changing---pushing---pr

**Describe what you would change to the page**
``` git clone git@github.com:USERNAME/rdmkit.git``` does not seem to be working for me.
I would recommend changing it with ``` git clone https://github.com/USERNAME/rdmkit/ ```.
If the former works for somebody, we could also display both options.

**Comment by GilOliveira** [comment]
>  `git clone git@github.com:USERNAME/rdmkit.git` does not seem to be working for me.

For that command to work you need to add your computer's SSH keys to your GitHub account. [See how here](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account)

**Comment by bedroesb** [comment]
@bianchini88 the current version is actually the recommended one, since it makes use of SSH keys and than you don't need to always set your credentials :) It must be that you have not set them up.

![image](https://github.com/elixir-europe/rdmkit/assets/44875756/af37cda9-c676-4a05-8ce3-5db249d04bfb)

I would give them both

Edit: @GilOliveira you where quicker ;)

**Comment by bedroesb** [comment]
Woops misclicked!

**Comment by GilOliveira** [comment]
> I would give them both

@bedroesb In that case maybe add a note letting people know that when you push it with HTTPS, you need to create a user token? That's the only way GitHub allows you to push using HTTPS.

**Comment by bianchini88** [comment]
@GilOliveira @bedroesb Thank you for this, I will have a look.

> you need to create a user token?

I remember I did that at some point, and I agree it is worth mentioning on the page.
