### ISSUE TITLE
Tutorial link is missing (404) 

### ISSUE THREAD

**Issue by gnewton** [elixir-europe/rdmkit#1482]
**Link to the page of interest**
https://github.com/elixir-europe/rdmkit/blob/master/working_with_git#the-advantage-of-working-locally-previewing-your-changes-through-your-web-browser

**Describe what you would change to the page**
Page returns a 404.

**List the tool(s)or resource(s) that are missing on the page (if applicable)**
Page is missing. Link from README.md
![Screenshot_2024-05-03_16-15-40](https://github.com/elixir-europe/rdmkit/assets/793478/7bfdca7f-88bc-41eb-99ac-7aa0bde7cfc0)

**Comment by bedroesb** [comment]
@gnewton thanks a lot for bringing this up, this should be resolved now!

**Comment by gnewton** [comment]
Thanks!  :-)
