### ISSUE TITLE
ensure (local) legal requirements

### ISSUE THREAD

**Issue by frederikcoppens** [elixir-europe/rdmkit#15]
Explore addition of requirements such as:

- [ ] imprints (e.g. German law ?)
- [ ] privacy statement (needed for GDPR ? What does GitHub track?)
- [ ] Accessibility statement
- [ ] Cookie policy?

**Comment by frederikcoppens** [comment]
added by Wolfgang Muller in google docs: 
GDPR: Looking at the site privacy statement (https://docs.github.com/en/github/site-policy/github-privacy-statement), they state that they do not collect any personal data in the relevant to GDPR: “We don’t knowingly collect information from children under 13, and we don’t collect Sensitive Personal Information.” . As the whole site does not collect this information, we are safe that our sub-site does not collect that information.

**Comment by bedroesb** [comment]
this is linked to #183
