### ISSUE TITLE
New your task page: Data discovery (including Beacon v2)

### ISSUE THREAD

**Issue by ainajene** [elixir-europe/rdmkit#1503]
**What topic do you wish to add?**
A new tool assembly page for Beacon v2, where we could explain how to implement a Beacon, the differents approaches and linked extensions. 

**Are there existing pages in the RDMkit website related to the requested page?**
Mentioned here: https://rdmkit.elixir-europe.org/human_data#sharing-and-reusing-of-human-data (under solutions)

**Resources**
https://docs.genomebeacons.org/
https://b2ri-documentation.readthedocs.io/en/latest/

**Context**
For the BY-COVID project, CRG is working on deliverable D2.3 (data discovery at source), which is due June 2024, and has been suggested that all the information explained in the deliverable related on how to light a Beacon should be documented here.

**Comment by bedroesb** [comment]
@ainajene thanks a lot for proposing this Tools assembly page. I would like to point out that in the tool assembly pages we mainly describe general concepts and ideas, of how tools can work together in tackling RDM related questions. (I know that the covid-19 data portal and galaxy tool assembly are exceptions). Detailed information on how to implement something is more appropriate in the FAIR Cookbook than in the RDMkit I would say. 

But maybe I am overthinking this! Is the content already written? (or can you be more specific about how detailed you would go). Than we could have a look with the editorial team on how we could make this work. And would you like me to create a Google doc to insert the content or would you work straight away in markdown?

**Comment by ainajene** [comment]
Hi @bedroesb ! There's information here and there in different github repos. However, for a deliverable in BY-COVID, you can find all the structured information there (section 5.3 [here](https://docs.google.com/document/d/1Obsfi4PwGztgZ0NJSKH-poqQY35zb4JStQeaa97USLA/edit?usp=sharing)). 

The WP2 leads suggested to add this information in the IDTk. However, this implementation is not unique to COVID-19. It can be implemented for any data. Hence, the change to RDMkit. 

This being said, I am by no means an expert in RDMkit vs FAIR cookbook. So I'll follow the instructions of the editorial team.

Thanks for taking time to review this issue!

**Comment by bedroesb** [comment]
@ainajene this is perfect! Let me put it on the agenda of the editorial meeting. I will follow up with more info once we can give you clear pointers.

**Comment by lauportell** [comment]
Hi @ainajene,
We discussed this during the editorial meeting - we realised that the RDMkit doesn't have a task page for data discovery at the moment. So, we thought it would be great to start this page, include the different types of discovery (cataloging and at source) and then include the Beacon piece. What do you think? Would that make sense for you?
If so, we can have a small meeting to start the page and I can help you adding some of the content as well :)

**Comment by ainajene** [comment]
Hi @lauportell, I'm happy with meeting and kick off the creation of this page. I could provide the information from the BY-COVID deliverable, however, I think that we need more data discovery experts for the general information (or at least review it).

**Comment by bedroesb** [comment]
A new task page about this would be great. Within our Editorial team / RDM community we for sure have the necessary experts available. And I think as editorial team we should make sure we indeed have the right people available for the reviewing! @lauportell will you setup the meeting between @ainajene ?

**Comment by lauportell** [comment]
Yes, I will meet with Aina to get this started!
