### ISSUE TITLE
Replace "scientific clusters" with "your science domain"

### ISSUE THREAD

**Issue by anenadic** [elixir-europe/rdmkit#1541]
Your science domain
 - bio medical sciences
 - social sciences
 - humanities
 - ...

**Comment by bedroesb** [comment]
Hello @anenadic, thank you for your proposal. Could you give more information on which page this is relevant to and be more verbose on on why?

**Comment by bedroesb** [comment]
@lauportell did you copy this issue over to the right place? 🙂

**Comment by lauportell** [comment]
already transferred to the right repo
