### ISSUE TITLE
Branding - acknowledgement grants

### ISSUE THREAD

**Issue by frederikcoppens** [elixir-europe/rdmkit#17]
Which projects / institutes do we need to acknowledge ?
Where and how do we do this ? About page ? Logos on home page ? ELIXIR in template so on each page ?

**Comment by CaroleGoble** [comment]
I added an acknowledgements.md file

**Comment by bedroesb** [comment]
We could do this in the footer if it is not too much

**Comment by CaroleGoble** [comment]
yes  -we need to work out all the funders

**Comment by bedroesb** [comment]
Footer and about page is added during the latest update. Does this give enough possibilities?

**Comment by bedroesb** [comment]
@martin-nc Can you check if we need the noral ELIXIR logo if we already have the converge logo?
