### ISSUE TITLE
Dealing with country specific tools

### ISSUE THREAD

**Issue by CaroleGoble** [elixir-europe/rdmkit#194]
**Many of the tools are country specific**
How do we use flags or some other mechanism to discriminate between and filter tools listed that are country specific

Use Case: DMP tools

- we don't want to have a long list of tools that are country specific

**Comment by floradanna** [comment]
A proposal could be to keep one csv table for all tools and resources (as it is now), and we just add an "accessible from" column where contributors specify if the tool/resource is accessible from "any country" or only from "X country".  Then, tools and resources tagged as  "accessible from any country" will be shown in the toolkit, while the tools and resources tagged as "accessible by X country" will be shown in the country-specific page of the toolkit.
