### ISSUE TITLE
Country specific advice

### ISSUE THREAD

**Issue by CaroleGoble** [elixir-europe/rdmkit#196]
**many pages have country specific advice**

For example Human data

we don't want to over board - we can recommend that the readers seeks country specific advice. 
But if we wanted to add LINKS to where that advice is, then we need a way of presenting that doesn't drown the page and can be kept up to date, And we need to be clear about synthesising the pan-country info

**Comment by floradanna** [comment]
The Jisc RDM toolkit solved the "Institute-specific issue" by adding a search box that link to universities' RDM webpage (see screenshot).
Maybe we could do the same for Country-specific guidelines, however every country (ELIXIR-Node) should have or should make a webpage about "National RDM", or a page where also information/links from the different universities and institutes are collected.


<img width="674" alt="Screenshot 2020-12-01 at 11 22 50" src="https://user-images.githubusercontent.com/51486716/100732136-9de04e00-33cc-11eb-92a9-cb78efcaed4e.png">

**Comment by floradanna** [comment]
Country guidelines about RDM in Life Sciences that are general for the whole Country. Laws, regulations, resources that apply to the whole country: 
- GDPR regulations
- laws on biological materials
- regulations about management of health data
- patents
- funders
- ethics committees
- national storage services
