### ISSUE TITLE
New page on  Data Management Expert Network(s) is needed

### ISSUE THREAD

**Issue by pinarpink** [elixir-europe/rdmkit#197]
**What topic do you wish to add?**

We need a page that introduces the ELIXIR Data Management Experts Network.
Optionally this page could also link to other expert networks such as the EJP RD FAIRification experts that were announced by Philip van Damme  at the beginning of day-2 of contenathon.  p.vandamme@amsterdamumc.nl (also see [slides](https://docs.google.com/presentation/d/19zJ0md86BbPr2PN41Hzmjye576rRbnj4KJ4YgCaxpF4/edit#slide=id.p6) ) 

**Are there existing pages in the RDM toolkit website related to the requested page?**
None yet.

**Resources**
CONVERGE Workpackage 1 was already working on establishing a web presence for the expert network. It would be good to link to that or to establish the page directly on the toolkit website. @nicjar would need to be contacted for specifics

**Context**
This was apparently discussed in the external relations meeting of the hub. Originally reported by @martin-nc  and @corinnemartin

**Comment by corinnemartin** [comment]
Just to add that the ELIXIR External Relations team indeed discussed the usefulness of a web presence for the expert network  - looking forwards to seeing one made, and do keep us in the loop of progress!

**Comment by Drosophilic** [comment]
This sounds a great idea!

**Comment by pinarpink** [comment]
This is now realized with https://elixir-europe.org/about-us/how-funded/eu-projects/converge/wp1/dm-coordinators
