### ISSUE TITLE
Ways of working - Governance

### ISSUE THREAD

**Issue by frederikcoppens** [elixir-europe/rdmkit#20]
Add a page to detail how the process works for adding content and ensuring consistency (editorial board etc)

Inspiration: https://github.com/alan-turing-institute/the-turing-way/blob/master/ways_of_working.md

This documents outlines expectations and responsibilities of project members and contributors of ELIXIR Data Management Toolkit with regards to working on the project.

Should this be a separate document or part of 'how to contribute'? 
Is 'ways of working' a good name ? Does 'governance' fit better ?

**Comment by martin-nc** [comment]
I think just one 'How to contribute' page sounds fine. Maybe start off with that page then see if it's necessary to add anything else? 'Governance' suggests something more formal and official, and it also sounds more stuffy!

**Comment by pinarpink** [comment]
We also have the following items related to Governance in the editorial was list in google doc.

- [ ] Privacy policy
- [ ] Takedown policy
- [ ] Complaints policy
- [ ] Code of Conduct

**Comment by bedroesb** [comment]
this issue will be replaced by a new issue focused on the editorial board
