### ISSUE TITLE
Create a Glossary

### ISSUE THREAD

**Issue by pinarpink** [elixir-europe/rdmkit#226]
We do not have a Glossary. We need one that will guide contributors and ensure consistency across page content.

This is a task transferred from the old editorial to do list  [here](https://docs.google.com/document/d/1eGRE26W2dgBpNGXsfZYvrOzCC_e1_o7oJdTJK7gW5uM/edit#)

This issue should be updated with existing glossaries that can be used across ELIXIR and elsewhere:

- A list of existing vocabularies can be found [here](https://www.rd-alliance.org/research-data-management-rdm-vocabularies-rda-10th-plenary-bof-meeting).
- For (sensitive) human data, the eTriks glossary [here](https://www.etriks.org/wp-content/uploads/2014/12/Code-of-Practice-on-Secondary-Use-of-Medical-Data-with-recognition.pdf) can be a good starting point.
- ...

**Comment by floradanna** [comment]
It is important indeed. Should we do this before the end of January?
Can we refer to an existing glossary or do we have to make our own?
If the page title of each RDM stage has a definition, this could be shown into the "summary" section maybe.

**Comment by floradanna** [comment]
WP3 decision:
Review and decide a glossary to adopt at the editorial meeting.

**Comment by smza** [comment]
Freezing this for now and possibly take it up later if needed.
