### ISSUE TITLE
Identify golden example pages.

### ISSUE THREAD

**Issue by pinarpink** [elixir-europe/rdmkit#227]
**Description**
We need few pages which reflect the expected contribution to the RDM toolkit. @floradanna suggests that we 3 example pages:

- one phase of the life cycle, (tools not needed on page)
- one problem 
- one domain.

the example pages can be used as reference when asking others for contributions.

@pinarpink  will try to circulate a poll  on this before the editorial meeting on 27 November.

**Comment by bedroesb** [comment]
@pinarpink What is the status of this?
