### ISSUE TITLE
A page for FAIR principles description

### ISSUE THREAD

**Issue by nicjar** [elixir-europe/rdmkit#281]
**Description**

**The FAIR principles** is a central concept that is referred to on many pages on the site. It would be good to have a standard place to link to regarding the description of FAIR, so that this is done consistently on all pages across the site. We avoid:

* Describing FAIR on every page that refers to it
* Having links to different descriptions (outside of the site) on different pages

The target could be a separate page, or part of e.g. the glossary (if we have one). As this is such a central concept, I'd prefer a separate page. _Not sure where in the structure it would fit, though..._ 😄

**Comment by floradanna** [comment]
We propose a FAIR page accessible from the landing page, explaining FAIR guiding principle and pointing to the rest of toolkit for how to make FAIR happen.

**Comment by martin-nc** [comment]
Just out of interest, is there a standard description of FAIR principles in ELIXIR that can be used/linked to across ELIXIR? Otherwise each ELIXIR resource might have their own version! Or do we need one specifically for the context of the toolkit?

**Comment by floradanna** [comment]
@martin-nc Good point, but I don't know. I didn't manage to find anything like that in ELIXIR website.

@OlivierCollin @rwwh @YvonneKallberg @wittigue We propose to use this page to talk about not only FAIR principles, but also to define what this RDMkit means with "**DATA**" (so, what is DATA here).
Some definitions below:
https://www.dtls.nl/fair-data/data-stewardship/ Digital data
https://www.oecd-ilibrary.org/sites/3631ee20-en/index.html?itemId=/content/component/3631ee20-en See box 1.2
https://rdm.elixir-belgium.org/data_in_dmp.html

**Comment by martin-nc** [comment]
This is the paper I've used in the past: https://www.nature.com/articles/sdata201618. I just couldn't find it yesterday! Siraa in the Hub says it's probably the one to use.

**Comment by rwwh** [comment]
http://fairprinciples.org/ currently refers to a page hosted at Go-FAIR that explains the principles and refers to the literature.

**Comment by smza** [comment]
Create a page and link it from the introductory text in the landing page?
