### ISSUE TITLE
Proposal for page metadata visualization 

### ISSUE THREAD

**Issue by bedroesb** [elixir-europe/rdmkit#298]
How it is now:

![Screenshot from 2021-01-04 15-01-38](https://user-images.githubusercontent.com/44875756/103543664-315ee000-4e9f-11eb-8b65-d4f5f1d6f207.png)

How it could be:

![Screenshot from 2021-01-04 14-46-22](https://user-images.githubusercontent.com/44875756/103543685-3b80de80-4e9f-11eb-9d4b-eb47a30a6cc1.png)

So it distinguishes better from the page content

**Comment by martin-nc** [comment]
@bedroesb looks good to me.
