### ISSUE TITLE
Possible additions to the data sharing page

### ISSUE THREAD

**Issue by pinarpink** [elixir-europe/rdmkit#375]
**Link to the page of interest**
https://rdm.elixir-europe.org/sharing

**Describe what you would change to the page**

Sharing is  where we should be linking the DataCite resource selector. Are there Data sharing tools? The" Tools and Resources" doesn't appear  in the data sharing page.

**Comment by pinarpink** [comment]
This is reported on behalf of @CaroleGoble

**Comment by floradanna** [comment]
"DataCite resource selector or re3data" should be added in the tool list and tagged with "data publication, researcher, data manager". In this way, it will appear in "Tools and Resources" in "Data Publication" page.

**Comment by floradanna** [comment]
I added DataCite resource selector=Repository Finder in the tool list.
