### ISSUE TITLE
Storage guidelines-WP1 DMNetwork

### ISSUE THREAD

**Issue by floradanna** [elixir-europe/rdmkit#376]
**Link to the page of interest**
https://rdm.elixir-europe.org/storage.html

**Describe what you would change to the page**
Define and give more details on different types of storage:
- for archiving, for analysis, for active storage, for share storage within research group...
- costs of each type of storage
- right storage type based on data type, data volume etc...

Content of storage page must be coordinated with the content of other pages to avoid confusion:
- [Preserve](https://rdm.elixir-europe.org/preserving)
- Repositories are already mentioned in "[Data Publication](https://rdm.elixir-europe.org/data_publication.html)" page
- [Data analysis](https://rdm.elixir-europe.org/data_analysis.html)

Contacts:
converge-wp1@elixir-europe.org
data-management-network@elixir-europe.org

**List the tool(s)or resource(s) that are missing on the page (if applicable)**
NA

**Comment by weiguUL** [comment]
in the "Considerations about the type of storage solution". I would suggest to add:
"1. Would the storage be accessible from your computing resources (e.g. HPC cluster, workflow management tools"
"2. If not (1): Do you have enough temperary (scratch) storage attached to the computing resources. How often do you have to transfer between the long-term storage and the temperay storage. How long does it take for each transfer (can be days or weeks for big files)"

**Comment by floradanna** [comment]
@smza, @flaviolic, @ooobik, @MarcusUppmax, @frederikcoppens, @OlivierCollin , @ntonello, @korbinib
Here you can find the content produced by the "[data storage focus group](https://docs.google.com/document/d/13goVwBsIYBoIVLYyBituDJ3z3NAdFmebOpbKXI5RTMs/edit#heading=h.x3bygkjwux4j)". I simply tried to shape the content written during the meeting according to the RDMkit template.

We would like to update the online page with this new content on Friday. Feel free to give suggestions on google doc until Friday; after that you can keep on improving the content directly on Github by making PR.
