### ISSUE TITLE
Fix an error in one of the tool/resource (MCPD)

### ISSUE THREAD

**Issue by afablondon** [elixir-europe/rdmkit#395]
**Link to the page of interest**
https://rdmkit.elixir-europe.org/all_tools_and_resources.html

**Describe what you would change to the page**
The MCPD metadata standard is linked to bio.tools, which end up with a blank page. It is not surprizing as it is not in bio.tools.
It should be linked to TESS : https://tess.elixir-europe.org/search?q=MIAPPE and FAIRsharing: https://fairsharing.org/FAIRsharing.hn155r

**List the tool(s)or resource(s) that are missing on the page (if applicable)**
- Name
- Link
- Description
- Registry (biotools or/and fairdome ID) (optional)

**Comment by bedroesb** [comment]
Thank you for notifying. Problem is that it does not link to a blank page, which is the reason why it is automatically linked to bio.tools. It is a coincidence that both the MCPD metadata standard and a software tool are similarly named. I will look into it

**Comment by bedroesb** [comment]
@afablondon In my personal opinion the MIAPPE material on TeSS should be tagged with MCPD so the user and me grammatically knows it is related

**Comment by afablondon** [comment]
Thank you: I will send a request on that to Cyril Pommier!

**Comment by bedroesb** [comment]
@afablondon I tackled this problem in PR #406 . Thank you for noticing this problem.
