### ISSUE TITLE
Adding a resource for the Plant domain

### ISSUE THREAD

**Issue by afablondon** [elixir-europe/rdmkit#396]
**Link to the page of interest**
https://rdmkit.elixir-europe.org/plant_sciences.html
https://rdmkit.elixir-europe.org/all_tools_and_resources.html

**Describe what you would change to the page**
Add GnpIS as a resource for community data sharing and re-use

**List the tool(s)or resource(s) that are missing on the page (if applicable)**
-Name: GnpIS
- Link: https://urgi.versailles.inrae.fr/gnpis/
- Description: A multispecies integrative information system dedicated to plant and fungi pests. It allows researchers to access genetic, phenotypic and genomic data. It is used by both large international projects and the French National Research Institute for Agriculture, Food and Environment.
- Registry (biotools or/and fairdome ID) (optional)
        - Fairsharing ID: FAIRsharing.dw22y3
        - bio.tools web link: https://bio.tools/t?page=1&q=GnpIS&sort=score
        - re3data web link: https://www.re3data.org/search?query=GnpIS

**Comment by bedroesb** [comment]
I added GnpIS in #400
