### ISSUE TITLE
FairdomHub should have a metadata tag

### ISSUE THREAD

**Issue by smza** [elixir-europe/rdmkit#397]
**Link to the page of interest**
https://rdmkit.elixir-europe.org/all_tools_and_resources.html

**Describe what you would change to the page**
Add metadata tag to the FAIRDOMHub in tools and resources

**List the tool(s)or resource(s) that are missing on the page (if applicable)**
NA

**Comment by floradanna** [comment]
Yes! You can add it in the google spreadsheet as described in the [Guide](https://rdmkit.elixir-europe.org/tool_resource_update.html#making-changes).

**Comment by bedroesb** [comment]
@smza I had to do some changes so I added it for you

**Comment by bedroesb** [comment]
done in #400
