### ISSUE TITLE
Tools table tags not updated

### ISSUE THREAD

**Issue by wittigue** [elixir-europe/rdmkit#399]
**Link to the page of interest**
https://rdmkit.elixir-europe.org/tool_resource_update.html

**Describe what you would change to the page**
The example tools table still contains tags for the life cycle stages (e.g. share, plan, collect) which are not used for the tools anymore.

And in the tags list for contributor (https://github.com/elixir-europe/rdmkit/blob/master/_data/tags.yml) there are also still cycle tags.

**List the tool(s)or resource(s) that are missing on the page (if applicable)**
- Name
- Link
- Description
- Registry (biotools or/and fairdome ID) (optional)

**Comment by bedroesb** [comment]
@wittigue the example table needs indeed an update. The tags in the tags.yml file on the other hand are not only used for the tagging of tools but also for the tagging of pages. This is why there are also cycle tags. But we should indeed make this more clear maybe

**Comment by bedroesb** [comment]
@wittigue Do you think that the changes in PR #404 do the trick?

**Comment by wittigue** [comment]
@bedroesb yes, looks good
