### ISSUE TITLE
Idea for the home page

### ISSUE THREAD

**Issue by martin-nc** [elixir-europe/rdmkit#405]
Just a quick thought: do we need the title on the home page? Can we just start with the grey box and put the full version of the site name in that:
![Screenshot 2021-02-10 at 10 19 47](https://user-images.githubusercontent.com/15261745/107496916-d4370800-6b89-11eb-9597-4e77de521478.png)
Perhaps that would be cleaner?

**Comment by bedroesb** [comment]
I like it ! Funny literately 3 mins ago I was thinking, why making the title mandatory?

**Comment by martin-nc** [comment]
Or even make the questions a little heading and lose the grey box:

![Screenshot 2021-02-10 at 12 39 14](https://user-images.githubusercontent.com/15261745/107511172-0aca4e00-6b9d-11eb-9b38-66c09dd328a2.png)

And maybe with the life cycle a bit bigger.
