### ISSUE TITLE
Improve listing of tagged pages

### ISSUE THREAD

**Issue by bedroesb** [elixir-europe/rdmkit#408]
Current situation for most pages:

![Screenshot from 2021-02-18 14-53-07](https://user-images.githubusercontent.com/44875756/108377265-26200380-7204-11eb-9f71-e3848d96519d.png)

except for the researcher role page:

![Screenshot from 2021-02-18 16-12-18](https://user-images.githubusercontent.com/44875756/108377331-37691000-7204-11eb-9ec9-7bdb9d86c837.png)

The option of using questions like in the researcher page is not sustainable and also not possible to automate. Something that would be possible is to add an extra line to the linked pages as extra information. 

This extra line can be a question:

![Screenshot from 2021-02-18 15-48-24](https://user-images.githubusercontent.com/44875756/108377556-74350700-7204-11eb-81af-44f2bac4a8e7.png)

Or my personal favorite, a small description/sentence about the question(s) that are tackled in the problem:

![Screenshot from 2021-02-18 16-11-59](https://user-images.githubusercontent.com/44875756/108377903-c8d88200-7204-11eb-9c74-a1ce82da4438.png)

**Comment by bedroesb** [comment]
The goal of giving a one-liner after the link would be to make it more inviting to click on it, like a little hint what it is about. Sou it does not look like a list of words with not much effort behind it

**Comment by bedroesb** [comment]
these one-liners would be part of the metadata of the given pages, and do not need (but could be) to be visualized on the given pages itself.

**Comment by wittigue** [comment]
I like the second option with the short description instead of questions. It would be great to have it as hidden metadata for the pages.

**Comment by martin-nc** [comment]
Both options are an improvement, I think. Perhaps the main thing is that the phrase explains the benefit the user will get from visiting the page, what problem will it solve. I would use a colon rather than a dash and not capitalise the description. It just looks neater to me:

> **Data protection:** ensure your research data complies to GDPR.

**Comment by bedroesb** [comment]
@martin-nc Also good for me!
Now we just need volunteers to write the lines :D

**Comment by wittigue** [comment]
I can do that. 
We only need that for the problem pages, right?

**Comment by bedroesb** [comment]
@wittigue ithem for sure, I don't know whether cycle pages are listed? @floradanna do you know that?

**Comment by floradanna** [comment]
Currently, only Problem pages are automatically listed in Life Cycle pages and in Role-Data steward pages. So, we would need description sentence only for problem pages.

In Role-Researcher page, the last two bullet points refer to different places: 
- capture --> Collecting page in Life Cycle
- my country --> ELIXIR website

**Comment by bedroesb** [comment]
@floradanna and @wittigue this #423 will allows to give a description in the metadata in this form:

```md
---
title: Compliance monitoring & measurement
tags: [plan, researcher, data manager, policy officer] 
contributors: [Christophe Trefois, Wei Gu, Pinar Alper]
description: a description
---
```

**Comment by bedroesb** [comment]
The easiest way might be to do it in this spreadsheet https://docs.google.com/spreadsheets/d/13vpg0T-Qf4EM3dAgJ0LSpuH8IbuuxVk_IgjA2LyYbuw/edit#gid=0

**Comment by wittigue** [comment]
my suggestions for the short descriptions of tagged pages.

Compliance monitoring: Measure and document data management capabilities
Data analysis: Best practices for data analysis
Data classification: Identify the type of your research data
Data Management Plan: How to write a Data Management Plan
Data organisation: Best practices to name and organise your research data
Data protection: Ensure your research data complies to GDPR
Data publication: Prepare your data and find repositories for publication 
Data quality: Ensure high quality research data
Data transfer: How to transfer large data files
Licensing: Consider licensing your research data
Metadata management: Find metadata standards and vocabularies
Data storage: How to find storage solutions

**Comment by bedroesb** [comment]
thanks @wittigue I wonder in which form we will display it? 

1) Data protection: ensure your research data complies to GDPR.
2) Data protection - Ensure your research data complies to GDPR

**Comment by wittigue** [comment]
I think I would prefer the second: 
Data protection - Ensure your research data complies to GDPR

**Comment by bedroesb** [comment]
or there other people that have a preference on this? @pinarpink @lauportell @floradanna @smza ?

**Comment by lauportell** [comment]
I would prefer the sentence better than the question I think. Makes it easier to understant what will be the content of the pages in my opinion.

**Comment by floradanna** [comment]
Personally, I prefer the style proposed by Martin "Data protection: ensure your research data complies to GDPR.", but both are fine.

I would propose the following _changes_ to the sentences:
Compliance monitoring: _measure compliance to DM regulations and standards._
Data analysis: _how to make data analysis FAIR._
Data classification: identify the type of your research data.
Data Management Plan: how to write a Data Management Plan (DMP).
Data organisation: best practices to name and organise your research data.
Data protection: ensure your research data complies to GDPR.
Data publication: prepare your data and find repositories for publication.
Data quality: ensure high quality research data.
Data transfer: _how to transfer data files._
Licensing: _how to license research data._
Metadata management: find metadata standards and vocabularies.
Data storage: _how to find appropriate storage solutions._

**Comment by lauportell** [comment]
I like your descriptions Flora, only I wouldn't say 'your' in the sentences, I would leave it neutral. Maybe also I would write data management instead of DM for compilance monitoring.

**Comment by floradanna** [comment]
Are these ok? Can we implement them?

Compliance monitoring: measure compliance to data management regulations and standards.
Data analysis: how to make data analysis FAIR.
Data classification: how to identify different research data types.
Data Management Plan: how to write a Data Management Plan (DMP).
Data organisation: best practices to name and organise research data.
Data protection: how to make research data compliant to GDPR.
Data publication: prepare data and find repositories for publication.
Data quality: ensure high quality research data.
Data transfer: how to transfer data files.
Licensing: how to license research data.
Metadata management: find metadata standards and vocabularies.
Data storage: how to find appropriate storage solutions.

**Comment by bedroesb** [comment]
Yes, will do it now, just to be sure, we do it this way: 
Compliance monitoring: measure compliance to data management regulations and standards.
and not 

Compliance monitoring: measure Compliance to data management regulations and standards.

**Comment by bedroesb** [comment]
woops misclicked, yes, will implement these sentences in my PR #423

**Comment by floradanna** [comment]
yes, correct.

**Comment by bedroesb** [comment]
![Screenshot from 2021-02-25 14-51-44](https://user-images.githubusercontent.com/44875756/109162894-0430fe80-7779-11eb-9f8b-0a522bda917b.png)

**Comment by lauportell** [comment]
I see in the screenshot that in metadata management it says 'ind' instead of 'find'

**Comment by wittigue** [comment]
I fixed it
