### ISSUE TITLE
Delete "External Links" paragraph

### ISSUE THREAD

**Issue by floradanna** [elixir-europe/rdmkit#409]
**Link to the page of interest**
All pages and template.

**Describe what you would change to the page**
Delete "External Links" paragraph from all pages and template. Move the present links to tool list or text.

**List the tool(s)or resource(s) that are missing on the page (if applicable)**

**Comment by floradanna** [comment]
Links that could be placed in the tools list and tagged:
- Data publication: 
  - [Welcome Open Research](https://wellcomeopenresearch.org/for-authors/data-guidelines)
- Licensing: 
  - [How to License Research Data](https://www.dcc.ac.uk/guidance/how-guides/license-research-data): how-to guide from the Digital Curation Centre (DCC).

**Comment by floradanna** [comment]
done

**Comment by bedroesb** [comment]
These sections are deleted in PR #415
