### ISSUE TITLE
Fixes to the Marine Metagenomics page

### ISSUE THREAD

**Issue by pinarpink** [elixir-europe/rdmkit#410]
**Link to the page of interest**
https://rdmkit.elixir-europe.org/marine_metagenomics.html

 
The following fixes are needed: 

- [x] There is no tools table. The resources mentioned in text would need to be placed a table at the bottom.
- [x] Links to MIxS, MIMS and MIMAG missing. We would expect these to be in the table as resources.
- [x] Links to trainings are missing.
- [x] Check the writing styling of sentences  (especially use of pronouns you vs I) and make sure it follows the agreed-upon style (this will be shared in the coming weeks by toolkit editors).

**Comment by DanFaria** [comment]
Done!
- Added tools to the tool list (MIMAG is not present anywhere other than a journal paper, so I didn't add it to the tool list)
- Added links to the tools
- Added link to training
- Revised writing style
