### ISSUE TITLE
Licensing vs. Licencing

### ISSUE THREAD

**Issue by wittigue** [elixir-europe/rdmkit#425]
**Link to the page of interest**
https://rdmkit.elixir-europe.org/licensing.html

**Describe what you would change to the page**
inconsistent use of Licensing/Licencing in this page
tab = Licensing
page title = Licencing
page tag = Licensing
page content = mixture of both

**List the tool(s)or resource(s) that are missing on the page (if applicable)**
- Name
- Link
- Description
- Registry (biotools or/and fairdome ID) (optional)

**Comment by martin-nc** [comment]
It should be 'licensing', I think. 

**Note for grammar bores like myself:** 
They might have been mixing it up with the noun 'licence'. In British English the noun is spelled with a 'c'  at the end ('licence'), but the verb is spelled with an 's' ('license'). In American English the noun and verb are both spelled with an 's' at the end. So whether British or American, the verb form has an 's' at the end.

"I bought a licence." (British)
"I bought a license." (American)
"You are not licensed to sell ice-cream." (British and American)

'Licensing' is a gerund (a verbal noun) so takes the verb form.

**Comment by floradanna** [comment]
English grammar rules have been applied to the page, according to the style guide.
