### ISSUE TITLE
Difference between Data sharing and Open data

### ISSUE THREAD

**Issue by floradanna** [elixir-europe/rdmkit#430]
**Link to the page of interest**
https://rdmkit.elixir-europe.org/sharing

**Describe what you would change to the page**
I think we should add a paragraph to clearly explain the difference between "sharing data" and "open access data".
Sharing datasets:
- Does not necessarily mean Open Access nor Public. (Meta)Data can be shared with Closed or Restricted Access.
- Does not have to happen immediately, while you are still working on the project. Data can be shared after your scientific paper is published.
- Is different from sharing your “result paper”. Difference between "Open access publications" and data.

**List the tool(s)or resource(s) that are missing on the page (if applicable)**
NA

**Comment by floradanna** [comment]
@lauportell Could you please look at this PR? We could merge this PR after your approval.

**Comment by lauportell** [comment]
@floradanna I was reading it right now and it all seems good to me. Thank you!
