### ISSUE TITLE
Add link to "ELIXIR Services software tools" on the Data Analysis page.

### ISSUE THREAD

**Issue by pinarpink** [elixir-europe/rdmkit#437]
**Link to the page of interest**
https://rdmkit.elixir-europe.org/data_analysis.html#

**Describe what you would change to the page**
Gary Saunders has suggested that a link can be added to [ELIXIR services software tools ](https://elixir-europe.org/services/tag/software-tools). This tool list also contains information about whether a tool is an ELIXIR recommended resource or not.

Instead of referring to individual tools it makes sense to refer to collections of tools such as this one. The addition can be on the Data Analysis page of RDMKit.

**List the tool(s)or resource(s) that are missing on the page (if applicable)**

- Name ELIXIR Services: Software Tools
- Link https://elixir-europe.org/services/tag/software-tools

**Comment by floradanna** [comment]
I would add the [ELIXIR services software tools ](https://elixir-europe.org/services/tag/software-tools) in the tool table tagged as: data_analysis.

We could also add the [ELIXIR Services: compute list](https://elixir-europe.org/services/tag/compute) in the tool table tagged as: data_storage, data_analysis, data_transfer.

**Comment by pinarpink** [comment]
We discussed the inclusion of the link to the "ELIXIR Software tools”. These tools are not focused on data management and the list does not appear to provide any information beyond links. As a result, it difficult to contextualise the list as an RDM resource for researchers and data stewards. So, we decided not to link to it from RDMKit at this stage. We informed Gary Saunders aswell.
