### ISSUE TITLE
Setting up Zenodo webhook for DOI

### ISSUE THREAD

**Issue by bedroesb** [elixir-europe/rdmkit#444]
We want maybe to link our releases to a DOI and push our content to Zenodo. Especially if we plan to have a publication about this.

**Comment by korbinib** [comment]
Is there a specific zenodo community this could be linked to e.g. 'ELIXIR Europe'?

**Comment by bedroesb** [comment]
Good question. Does that exist even?

**Comment by martin-nc** [comment]
I've just asked. Apparently someone set up an ELIXIR community space on Zenodo but it didn't get used. There are plans to resurrect the space but it's not active at the moment.

**Comment by korbinib** [comment]
Pushing this awards again, Would be nice to include a doi in D3.2. The Zenodo entries can be allocated to a community at any time point.

**Comment by bedroesb** [comment]
I added a webhook towards Zenodo. The current plan would be to make a release for 1.1 and that we add the previous two releases manually to Zenodo. The upload will be linked to the ELIXIR Europe comunity.

**Comment by bedroesb** [comment]
Webhook is in place and working
