### ISSUE TITLE
Improve Plant domain page

### ISSUE THREAD

**Issue by wittigue** [elixir-europe/rdmkit#453]
**Link to the page of interest**
https://rdmkit.elixir-europe.org/plant_sciences.html

**Describe what you would change to the page**
Section "Keep the connection between phenotyping and genomic data" needs some spell checking and partially re-writing. At the end of this section it looks like information is missing.
Plant Genetic Resources like EURISCO (https://eurisco.ipk-gatersleben.de) could be also mentioned here.

**List the tool(s)or resource(s) that are missing on the page (if applicable)**
- Name
- Link
- Description
- Registry (biotools or/and fairdome ID) (optional)

**Comment by wittigue** [comment]
@DanFaria: let me know if you have the missing text for the last section already somewhere. I could make the changes.

**Comment by DanFaria** [comment]
Thanks @wittigue. I'll take care of it in the next couple of days.

**Comment by DanFaria** [comment]
Done!
