### ISSUE TITLE
No LIMS in the RDMkit

### ISSUE THREAD

**Issue by CaroleGoble** [elixir-europe/rdmkit#517]
We appear to be completely silent in the RDMkit about LIMS systems. Yet LIMS are **critical** to data management, esp in the collection stage, which is a bit thin TBH.

This is a general point that the RDMkit emerged from ELIXIR and ELIXIR is all about data archives and not enough about data in the labs. We need to look beyond the tools offered by ELIXIR if we truly advise researchers. And that means acknowleding LIMS systems!

**Comment by korbinib** [comment]
Maybe openBIS and the qbic tool assembly could be a starting point to include as open source solutions
