### ISSUE TITLE
Suggestion to replace 'Your problem'

### ISSUE THREAD

**Issue by Nazeeefa** [elixir-europe/rdmkit#530]
Hi! I think it sounds better if we replace 'Your problem' with 'Your query' or 'Your task'. Not all the things listed under 'Your problem' are necessarily data management problems or should be viewed as a problem. 

The aim is to encourage and help a reader to understand and appreciate the importance of data management steps. As compared to the term 'problem', query or 'task' suggests that data management steps must be addressed rather than a problem/issue that needs to be solved or can be ignored if it's not a problem.

Happy to know your thoughts and learn from your views! Thank you :)

**Comment by rwwh** [comment]
When considering alternatives, take "Your challenge" into consideration.

**Comment by floradanna** [comment]
Tasks or RDM tasks or Common tasks

**Comment by rwwh** [comment]
I like common tasks

**Comment by martin-nc** [comment]
Yes, my vote would be for 'Common tasks', or keep the pattern of the 'role' and 'domain' sections, and go for 'Your tasks'. I'd break the pattern slightly by making 'task' plural, because 'Your task' sounds like we're giving people a challenge!

**Comment by Nazeeefa** [comment]
Yes, '**Your Tasks**' sounds fine. 

Common tasks can give an impression it's a simple task and 'simple' can have a connotation of 'not so necessary' to some readers, that may not allow to highlight importance as much. Also, it may raise a question that there are tasks that may be uncommon.

**Comment by pinarpink** [comment]
+1 for "Common tasks"

**Comment by lauportell** [comment]
I like 'Common tasks' as well

**Comment by Nazeeefa** [comment]
I'll stick to what I suggested 'Your task' and, based on @martin-nc and @floradanna mentioned, like the idea of using 'Your tasks' or 'Your RDM tasks'. It's easy to understand, when I look at content from first-time user/reader's point of view.

**Comment by smza** [comment]
I agree with Nazeefa, I prefer 'Your Task'  of 'Your RDM Task'. This sales more relevant and kind of fits in.

**Comment by bedroesb** [comment]
If I have to choose between 'Your task(s)' or 'Common tasks', I prefer 'Your task(s)' for the same reason that it follows the same structure
