### ISSUE TITLE
RDMkit logo on Data Lif Cycle wheel in mediakit

### ISSUE THREAD

**Issue by bedroesb** [elixir-europe/rdmkit#545]
As discussed in our last meeting, I would make some variations on how we could attribute our brand in the data life cycle diagram. This design will exist next to the life cycle without the RDMkit logo (like it is now). It would serve as a branded alternative to attribute RDMkit for those that want to. Since it are alternatives, we can support multiple variations off course.

These designs ill be available on the mediakit, but maybe we can also use one of these on our front page?

Please comment below the number you prefer (or a total other suggestion) and why you like it.

1)

![data_life_cycle_1](https://user-images.githubusercontent.com/44875756/117676049-7b3d3700-b1ad-11eb-8336-030f17dc1b5d.png)

<hr>

2) 

![data_life_cycle_2](https://user-images.githubusercontent.com/44875756/117676095-8728f900-b1ad-11eb-96ac-d498e4094091.png)
<hr>

3)

![data_life_cycle_3](https://user-images.githubusercontent.com/44875756/117676138-90b26100-b1ad-11eb-9eec-8f2c4d4bd922.png)
<hr>

4)

![data_life_cycle_4](https://user-images.githubusercontent.com/44875756/117703529-0af0de80-b1ca-11eb-91ac-538a74a7dae8.png)
<hr>

5)

![data_life_cycle_5](https://user-images.githubusercontent.com/44875756/117703480-fb719580-b1c9-11eb-9272-4bb5cc5db2be.png)
<hr>

6)

![data_life_cycle_6](https://user-images.githubusercontent.com/44875756/117676200-9ad45f80-b1ad-11eb-8e52-3bb4dc0e9f89.png)
<hr>

7)

![data_life_cycle_7](https://user-images.githubusercontent.com/44875756/117676223-a0ca4080-b1ad-11eb-89d7-1bedcd156565.png)
<hr>

8)

![data_life_cycle_8](https://user-images.githubusercontent.com/44875756/117676237-a58ef480-b1ad-11eb-86c9-9f609f094548.png)
<hr>

9)

![data_life_cycle_9](https://user-images.githubusercontent.com/44875756/117676261-ab84d580-b1ad-11eb-8529-b215fdc1f864.png)
<hr>

**Comment by floradanna** [comment]
8

**Comment by lauportell** [comment]
3 or 9

**Comment by martin-nc** [comment]
It seems a bit odd to brand something that is very similar to what others use:

- https://www.nexor.com/resources/white-papers/enabling-secure-information-exchange-in-cloud-environments/
- https://roaringelephant.org/2019/01/15/episode-123-infrastructure-and-data-lifecycle-part-2/
- https://www.fws.gov/data/

Where would this diagram be used? Sorry - I must have missed or forgotten the conversation.

**Comment by wittigue** [comment]
9

**Comment by pinarpink** [comment]
8 & 9

**Comment by bedroesb** [comment]
I could off course put multiple flavors online so the people can choose ...

**Comment by scapella** [comment]
It would be important to clarify the origin of this diagram. If I can correctly remember the initial conversations on Converge, this way to represent the RDM life-cycle comes from another project/initiative/official programme (I think from the UK). Thus, the original reference - I think - should be acknowledged saying this is a derivative work (licenses permitting).

Once it is clarified, I'd vote for 9 (first) and 8 (second).

**Comment by martin-nc** [comment]
I'd go for 9 then 8.

**Comment by bedroesb** [comment]
@scapella From what I know the current one is inspired by the many out there and not originating from one specific data life cycle wheel This is also one of the reasons we want to give the option to use a non branded one. I guess you are talking about this one:
- https://www.reading.ac.uk/research-services/research-data-management/about-research-data-management/the-research-data-lifecycle

But i find for example also this one which is the same:

- https://biblio.uottawa.ca/en/services/faculty/research-data-management/what-research-data-management

**Comment by martin-nc** [comment]
The life cycle idea came from the first RDMkit hackathon last July, where we had a design breakout team who looked at other websites for inspiration. You can see the ideas here:
https://drive.google.com/drive/folders/1cTq2YYkshcClk0qoj2y-GNqySccJI_Ex

I think the [JIISC one](https://rdmtoolkit.jisc.ac.uk/research-data-lifecycle/) was the first we saw that used the diagram as a navigation tool, but there are many similar diagrams.

**Comment by scapella** [comment]
Thanks for the pointers. Indeed, there is a lot of resemblance with the
JIISC one.
Impact is one of the strategic areas in ELIXIR at the moment. Thus,
recognizing others impact via attribution is also a nice action to take.
Said that I let you deciding any particular step in this direction.

Salva

**Comment by frederikcoppens** [comment]
8
