### ISSUE TITLE
New page - Epitranscriptome data

### ISSUE THREAD

**Issue by lauportell** [elixir-europe/rdmkit#565]
**What topic do you wish to add?**
Epitranscriptome data page as a Domain of the RDMkit - it is one of the use-case from ELIXIR Converge WP5.

**Are there existing pages in the RDMkit website related to the requested page?**
This will be added to the 'your domain' section of RDMKit

**Resources**
https://docs.google.com/document/d/1L96RhwhAsmQPyU0CKm0L7DpTiOdlhBxw3JsfoLKnnJ4/edit?usp=sharing

**Context**
ELIXIR Converge WP5

**Comment by bedroesb** [comment]
I was just working a PR that adds the page to the sidebar, I will keep you updated!

**Comment by bedroesb** [comment]
@lauportell I made a PR #569  that adds the page to the sidepanel + adds the tools. Do you think this is what you needed?

**Comment by lauportell** [comment]
page is created
