### ISSUE TITLE
Tool assembly - CSC (ELIXIR-FI)

### ISSUE THREAD

**Issue by siirif** [elixir-europe/rdmkit#566]
**What topic do you wish to add?**
This is an example of a Data Management tool assembly, CSC – IT Center for Science is a Finnish center of expertise in information technology. CSC provides high-quality ICT expert services for researchers in Finland and their collaborators, more precicely higher education institutions, research institutes, culture, public administration and enterprises.

**Are there existing pages in the RDMkit website related to the requested page?**
Tool assembly pages

**Resources**
If there are there resources that could be utilised for writing the new page, please list them below:
Our google docs
https://docs.google.com/document/d/1CFJmYfiRMKCHnNSDI6IpHuHk66r38EGe2kYF66Gqqy8/edit#

**Context**
If this request is coming from a particular project, domain, or use-case please list them below:
26.5.2021 toolkit contentahon for tool assemblies

**Comment by siirif** [comment]
Hi! I was wondering whether it is possible to modify the picture on the page? I made the original version, but it was redone by someone else, hence, I don't really know how to fix it myself. 
The original is here: https://kannu.csc.fi/s/XHirMDTb37rbQfA

The main issues: 

- In the middle of the pic Fairdata IDA is misspelled (FAIRdata IDA --> Fairdata IDA)
- Preserve & Share: Fairdata.fi Etsin --> it is nice one has added the "logo" themselves, but then the same could be in Fairdata IDA as well (https://ida.fairdata.fi/login) or then just have it written "Fairdata Etsin"
- It was on purpose in publishing part that "Federated EGA" and "SD Submit" are both at the "same level" because both can be used. SD submit is for all kinds of sensitive data, where as Federated EGA is for human omics data. 
- the text under plan, collect etc. is super small! very difficult to read.

How can could I proceed with fixing these issues? 
Thank you already in advance for your help! :)

**Comment by bedroesb** [comment]
@korbinib I think you helped out with these pictures no? Can you have a look?

**Comment by korbinib** [comment]
![fi_csc_assembly](https://user-images.githubusercontent.com/58505673/150968917-7a50f2c7-c7f8-44c8-91d6-d1a84a91207c.svg)

@siirif  - Does this fit with your idea? I can recommend e.g. [inkscape]( https://inkscape.org/) as an open source tool for svg editing.

**Comment by siirif** [comment]
Thanks Korbinian, looks fine!
