### ISSUE TITLE
Tools assembly - IFB (ELIXIR-FR)

### ISSUE THREAD

**Issue by OlivierCollin** [elixir-europe/rdmkit#570]
**What topic do you wish to add?**
a first version of a Data Management tools assembly by IFB (Institut français de Bioinformatique - French Bioinformatics Institute) and ELIXIR France. IFB is a french national bioinformatics infrastructure and offers services to support research projects in Life Sciences by provisioning an IT infrastructure distributed across the country. 

**Are there existing pages in the RDMkit website related to the requested page?**
Tools assembly menu

**Resources**
If there are there resources that could be utilised for writing the new page, please list them below:
- https://docs.google.com/document/d/1E6GsE3L2zsYjKicI_VotIuYXVKS41H3hRWr7YUsAdmo/edit

**Context**
If this request is coming from a particular project, domain, or use-case please list them below:
Tools Assembly contenthaton - 26-27/05/2021

**Comment by floradanna** [comment]
@OlivierCollin please use this page for your PR: https://github.com/elixir-europe/rdmkit/blob/master/pages/tool_assembly/fr_ifb_assembly.md
