### ISSUE TITLE
Refinement git contribution guide

### ISSUE THREAD

**Issue by korbinib** [elixir-europe/rdmkit#574]
**Link to the page of interest**
https://rdmkit.elixir-europe.org/working_with_git.html

**Describe what you would change to the page**
Include more details on adding new pages, including templates.

**Comment by jburel** [comment]
adjustment made to the page in https://github.com/elixir-europe/rdmkit/pull/600 to include the Docker option

**Comment by bedroesb** [comment]
@korbinib Since making new pages is an editor task I added this info to [the editorial board guide](https://rdmkit.elixir-europe.org/editorial_board_guide.html)

**Comment by korbinib** [comment]
@bedroesb looks great to me. Will close the issue.
