### ISSUE TITLE
Index page for tools assemblies

### ISSUE THREAD

**Issue by korbinib** [elixir-europe/rdmkit#575]
**What topic do you wish to add?**
Index page for tools assemblies to include more details about the different assemblies and the respective target audience.

**Are there existing pages in the RDMkit website related to the requested page?**
Yes, the tools assemblies.

**Context**
If this request is coming from a particular project, domain, or use-case please list them below:

This is an idea coming up during the contentathon in May 2021

EDIT: Related issues: #196 #194

**Comment by korbinib** [comment]
One possible approach could be a table with one column for all the tags the respective tool assembly uses.

**Comment by bedroesb** [comment]
This page would list the assemblies with following (meta)data:
- Name
- Description
- Tags
- Tools it uses
- Country?

**Comment by bedroesb** [comment]
I was thinking of making an array of cards like on the frontpage, @korbinib @martin-nc what dou you think?
These cards could be automaticall generated based on the metadata in the tools assembly pages

**Comment by korbinib** [comment]
What would be the cards then? E.g. domain specific tools assemblies, national/institutional tools assemblies, ...? Initially I thought about a table, but this is of course less appealing presentation wise.

**Comment by bedroesb** [comment]
I thought of having a card for every assembly, I could make an example for this next week.

**Comment by korbinib** [comment]
I think one card per assembly works well for a limited number but might get convoluted for a large(r) number.

**Comment by bedroesb** [comment]
hmmm maybe you are right. I don't know how many assemblies we plan to have in the future. We could multiple columns and maybe we can give some filter options. A table would for sure be easier.

**Comment by martin-nc** [comment]
If it's possible to tag them by problem they're addressing you could use something like the isotope library with cards:
https://isotope.metafizzy.co/filtering.html. You could filter the cards by tags. I'm not sure if the tags could contain enough information, though.

If there aren't many assemblies, then the table sounds okay. If there were a lot of them then maybe it would be better to classify them by problem they solve, if that's possible?

**Comment by korbinib** [comment]
This could be nice.

>  If there were a lot of them then maybe it would be better to classify them by problem they solve, if that's possible?

I think the closest we have to this it the problem pages they refer to, but this is not formalized (yet). Maybe something to worry about when we have a substantial number to worry about.

**Comment by bedroesb** [comment]
I did a sketchy start of the cards here #586
