### ISSUE TITLE
Tool(s) Assembly

### ISSUE THREAD

**Issue by DanFaria** [elixir-europe/rdmkit#583]
I just noticed we changed Tool Assembly to Tools Assembly, which is grammatically incorrect.
Tool assembly is a (spaced or open) compound noun, and it already means an assembly of tools, much like cat food means food for cats (and not a single cat).

**Comment by martin-nc** [comment]
Yes, you're right. @korbinib sorry - I was a bit hasty in approving that change. I was assuming it was a term already used in that world. I guess from @DanFaria's comment there isn't a standard term. 

Just as an afterthought: if it isn't a standard term, then what else do people call these things? Is there a more commonly-used term for tool assemblies?

**Comment by korbinib** [comment]
It has been Tool**s** assemblies on the menu and the other parts. Hence I adapted this on the NeLS description and elsewhere to establish consistency. I was somehow assuming there was an earlier discussion on this with the opposite outcome. Should we role back things? [And we will have to be careful about the currently drafted tool"s?" assemblies and the upcoming event.]

**Comment by korbinib** [comment]
> Just as an afterthought: if it isn't a standard term, then what else do people call these things? Is there a more commonly-used term for tool assemblies?

I think toolkit is used more often, but not too close to the RDMkit I assume?

**Comment by martin-nc** [comment]
Oh, I hadn't noticed the spelling in the menu! I've just Googled 'tool assemblies', 'tools assemblies', 'tool assemblies bioinformatics' and related phrases, but couldn't find anywhere that people used those terms (outside ELIXIR, at least). I'm not aware of a formal decision being made about the terminology, but perhaps there was. 

If the decision needed to be made now then my vote would be to revert it back, but if it wasn't urgent then maybe it would be something to discuss at the next meeting?

**Comment by bedroesb** [comment]
Did something change recently? Because I have been using `Tools assembly` the way it is now on the website for quite some time now. If we decide on changing it please ping me so I can change/check it everywhere! I remember we had a discussion about this in the past with @floradanna but don't remember the details.

**Comment by martin-nc** [comment]
@bedroesb I think the only thing that has changed on the site is that @korbinib added 'Tools assembly' to the style guide (https://github.com/elixir-europe/rdmkit/pull/571) because that is what we already use, but @DanFaria is pointing out that it's not grammatically correct. It should be 'Tool assembly'.

**Comment by DanFaria** [comment]
I remember it being "tool assembly" in the menu before. Not sure how long ago.
Carole always talked about tool assemblies, so not sure we should be looking for an alternative term without her on the loop.
Anyway, tool assembly does exist as a term in the industry: https://en.wikipedia.org/wiki/Tool_management#Tool_assemblies

**Comment by floradanna** [comment]
Hi, I don't remember how it was called before or why it was changed.
Whatever the name is, it must be grammatically correct. So, I suggest to change it to make it grammatically correct everywhere.

I am not sure if the same grammar rule apply to other cases, such as "Tool list" vs "Tools list" or "Tools table" vs "Tool table". These are words that maybe have been used.
