### ISSUE TITLE
Costs for data management

### ISSUE THREAD

**Issue by siirif** [elixir-europe/rdmkit#593]
**What topic do you wish to add?**
We can write with about "Costs for data management", which was a topic on the gap sheet: 
https://docs.google.com/spreadsheets/d/1k7lSEKhXqAuzQi_YktQI09iI0nAMkcOr5UxtR3SBdqk/edit#gid=1521145424

**Are there existing pages in the RDMkit website related to the requested page?**
There is an existing page about Data Management Plans, but should this be part of that or an own page I am not sure.

**Resources**
If there are there resources that could be utilised for writing the new page, please list them below:

We will first write a draft on a google docs so we can work together (we will only start after summer holidays)
https://docs.google.com/document/d/1wXfHxMDCYB0tjUSFRkHvF5sAuRGrncXH5maYkCGoJx4/edit#heading=h.6pr2zdod4u5e 

**Context**
If this request is coming from a particular project, domain, or use-case please list them below:

**Comment by floradanna** [comment]
Hi, thanks for proposing this important topic.

Giving guidelines and best practices about costs for data management is quite a challenge since costs vary a lot depending on discipline, country, institute etc. 

Do you already have an idea about how to address this topic? For instance, are you going to provide price range for specific tools or services, or are you going to explain what items/aspects need to be into account as data management costs?

**Comment by siirif** [comment]
Hi!
The idea was to write about things that should be taken into consideration when budgeting data management so not giving prices or anything. Hence, this could be also a sub topic of data management.

**Comment by korbinib** [comment]
Hi,
Many of the costs are related to time spent on RDM or RDM as a service from a 3rd party paid by the hour. Maybe we can also include estimates for time efforts needed for specific tasks?

**Comment by siirif** [comment]
Well my original idea with @minnami was just a guidance text about costs for data management, which would include time and money needed for managing data well. 
So write a nice text about issues below:

Estimate the resources needed (for example, financial and time) to manage, preserve and share the data. Consider the additional computational facilities and resources that need to be accessed, and what the associated costs will amount to.

Tips for best practices:
*Remember to specify your data management costs in the budget, according to funder requirements.
*Account for the costs of the necessary resources (for example, time) to prepare the data for sharing/preservation (data curation). Carefully consider and justify any resources needed to deliver the data. These may include storage costs, hardware, staff time, the costs of preparing data for deposit and repository charges.

**Comment by floradanna** [comment]
Hi @siirif, do you have any news about this page? If I can help with something, please let me know.

**Comment by siirif** [comment]
Hi @floradanna!  We might have had a misunderstanding here: we though with @minnami  that you didn't like our idea so we didn't work on this. However, if people think this is a good idea, we are happy to write about this topic or have a focus group in WP1 (best practice guidelines). :)

**Comment by floradanna** [comment]
Sorry for the misunderstanding. I do like the idea and I think that it is a very important topic to be addressed in RDMkit.
If you already have enough materials and knowledge to write a starting content, I would suggest that you go ahead with writing.
If you prefer to have 1 focus group, please let me know and I will propose it as a topic in WP1.

**Comment by siirif** [comment]
We don't have yet material, just ideas :) 
As everyone, we are super busy right now, so it will take some time we are able to produce a draft. 
If this is urgent, then let's make a focus group so more people can participate :)

**Comment by lauportell** [comment]
Hi @siirif do we have already some materials to start this and move forward?

**Comment by siirif** [comment]
Hi and good new year! We just came back from holidays and have not started on this. We will discuss this week with @minnami  if we can make some sort of draft and then other could also contribute on the subject!

**Comment by floradanna** [comment]
Great, thanks!

**Comment by floradanna** [comment]
This is one of the topic that has been selected during the WP1 F2F meeting in Padova to be addressed in RDMkit.

[Google doc from WP1.](https://docs.google.com/document/d/1QgWyD73AyhP3B8dZ4Lu91RzqY_q11GAW9MQVloWKNPc/edit#heading=h.58yb4u5em02r)

**Comment by minnami** [comment]
Yes, thanks! There is now a group of people working on this.

**Comment by siirif** [comment]
I guess the v1 of this topic is done, one can find it here: https://docs.google.com/document/d/1QgWyD73AyhP3B8dZ4Lu91RzqY_q11GAW9MQVloWKNPc/edit# I did not find a page for this, so I didn't bring it to github yet.

**Comment by bedroesb** [comment]
@elixir-europe/rdmkit-editors I think we can start making a page for this

**Comment by siirif** [comment]
Hi! Just wondering, if there is already a page for this?

**Comment by floradanna** [comment]
Hi! No, not yet. I can make later this week, unless another editor @elixir-europe/rdmkit-editors creates it sooner.

**Comment by Nazeeefa** [comment]
@lauportell I am creating it at the moment, already. Almost done.

**Comment by Nazeeefa** [comment]
@siirif @minnami it is here https://github.com/elixir-europe/rdmkit/pull/1171 I moved the first heading after description. I think page needs some revision.

**Comment by siirif** [comment]
Hi! We are done with this page content under Nafeeza's branch and I added 3 tools the the tools table. Could someone get this page online? :)

**Comment by Nazeeefa** [comment]
Hi @siirif Thank you for letting me know, we'll take care of it 👍🏽 
Also, thank you for the correct spelling of my name :)
