### ISSUE TITLE
Adding Person and Organisation metadata to website

### ISSUE THREAD

**Issue by bedroesb** [elixir-europe/rdmkit#597]
Adding Bioschemas for [Person](https://bioschemas.org/profiles/Person/0.2-DRAFT-2019_07_19/) and [Organisation](https://bioschemas.org/profiles/Organization/0.2-DRAFT-2019_07_19/)

**Comment by bedroesb** [comment]
proposal by @jburel to add schema.org for events

**Comment by jburel** [comment]
* https://github.com/elixir-europe/rdmkit/pull/599#discussion_r652455333
* https://github.com/elixir-europe/rdmkit/pull/599#discussion_r652496430
