### ISSUE TITLE
Translational Biomedicine Tool Assembly

### ISSUE THREAD

**Issue by pinarpink** [elixir-europe/rdmkit#602]
**What topic do you wish to add?**
A tool assembly page describing the assembly of RDM tools to support Translational Biomedicine projects.

**Are there existing pages in the RDMkit website related to the requested page?**
https://rdmkit.elixir-europe.org/data_protection.html
https://rdmkit.elixir-europe.org/human_data.html
https://rdmkit.elixir-europe.org/data_quality.html

**Resources**
We will utilise documentation of several Translational Biomedicine projects, which deploy the same assmbly, such as [BIOMAP](https://imi-biomap.pages.uni.lu), COVIRNA, HeartMed.

**Context**
This page request is issued as part of the tool assembly contentathon.

**Comment by lauportell** [comment]
Page already up in the RDMkit
