### ISSUE TITLE
Suggestion: Display life cycle with step(s) highlighted relevant to each topic (listed under 'Your problem')

### ISSUE THREAD

**Issue by Nazeeefa** [elixir-europe/rdmkit#606]
Displaying highlighted relevant step(s), in data life cycle, can help a reader later in understanding and creating a data management plan. Here, think of data life cycle step(s) as criterion/criteria that are met/covered when addressing a data problem/challenge.

Example display (data life cycle on right) and with following caption: _Identifiers are key part of **data collection** that allow to make data interoperable. Identifiers, as part of metadata standards, enable easy **data sharing** and **data reuse**. Using identifiers help to cover data life cycle stages highlighted in this figure._
<img width="1346" alt="DataLifeCycles_For_Identifiers" src="https://user-images.githubusercontent.com/6730853/122623265-bfb8ce00-d09b-11eb-9cab-2fefbd93bfaa.png">

I understand there are topics, listed under 'Your problems', that are required to be covered through all life cycle stages such as  data organisation and data documentation - in that case, maybe highlighting first or main step when those "problems" should be addressed can be helpful for a reader.

Happy to know your thoughts and learn from your views! Thank you :)

**Comment by martin-nc** [comment]
@Nazeeefa Thanks for that - it's an interesting idea. A couple of thoughts from me:

1. We currently use the RDM life cycle diagram in the side menu, and highlight the section you are in. So if you are on the Planning page, then the 'Plan' section of the diagram is highlighted. If we included the diagram in the page as you suggest and highlight various sections, people might get confused. They might think the diagram is trying to tell them where they are in the site, even when they are not in a 'life cycle page'! I would use it at the bottom of the page instead, where it won't get muddled with the menu diagram, and where it won't distract too much from the main content. 
2. The bigger question is: would it be useful? We already have the tags at the bottom of the page that include related sections from the life cycle. Would the diagram add more to that? I don't know the answer to that. Would it give the life cycle more prominence than it deserves? I mean, if some people didn't feel that the life cycle related directly to their problems then maybe it's not so relevant. On the other hand, it could be a way of tying the bits of the site together into one theme (the life cycle).

I think we need to see what others think, especially about point 2.

**Comment by Nazeeefa** [comment]
Thank you @martin-nc for sharing your thoughts! :)

1. The diagram will have caption, as I mentioned example caption above, to avoid any confusion. Also, in context of this suggestion/idea, the data life cycle steps do not have to be displayed in a circular form and can be displayed, for example, in linear form (if there is a space at the top or bottom of page). In case there is very limited space, what we can alternatively do is display only relevant/highlighted steps instead of all.

2. The purpose of diagram here is to help reader appreciate the life cycle steps that will be covered as they handle data in FAIR manner, thereby helping to raise awareness that FAIRness of data is crucial. "...If some people didn't feel that the life cycle related directly to their problems then maybe it's not so relevant" - I appreciate your view. As I understand, one aim of 'Your Problems' page in RDMkit is to also help reader understand that addressing topics (listed under 'Problems') help make data FAIR and therefore are interconnected with data life cycle.

Diagram is useful as it serves as a visual content. Currently, as I see, there is mainly written content on pages that can make information appear verbose and make reader overwhelmed discouraging them from going through it all. Having visual content helps to digest information.

Happy to know further thoughts and learn more! Thank you.

**Comment by Nazeeefa** [comment]
@martin-nc No worries, thank you for letting me know. I'll close the issue.

The suggestion for showing relevant steps, from data life cycle, was mainly for 'Your tasks' pages.

Thank you for reading and sharing your views, I appreciate your time.
