### ISSUE TITLE
Marine metagenomics tools assembly

### ISSUE THREAD

**Issue by lauportell** [elixir-europe/rdmkit#614]
**What topic do you wish to add?**
A tool assembly page describing the assembly of RDM tools to support Marine Metagenomics projects.

**Are there existing pages in the RDMkit website related to the requested page?**
https://rdmkit.elixir-europe.org/marine_metagenomics.html

**Resources**
https://docs.google.com/document/d/1GN7p55ZotNNPtX85B-h6yZJwxvNXMUHOPjabIcBZGus/edit

**Context**
This page request is issued as part of the tool assembly contentathon.

**Comment by Workberg** [comment]
I think the text is ready now. Korbinian is converting the figure to svg.
