### ISSUE TITLE
Separate new page on Ethics

### ISSUE THREAD

**Issue by pinarpink** [elixir-europe/rdmkit#616]
**What topic do you wish to add?**
While reviewing the human data page we realised the Planning section discusses ethics and informed consent but it does not go into details of solutions. 

**Are there existing pages in the RDMkit website related to the requested page?**
The Ethics page is closely related to the Data protection page. It should however be a separate page.

**Resources**
If there are there resources that could be utilised for writing the new page, please list them below:

**Context**
This is needed in the context of Human Data use case.

**Comment by pinarpink** [comment]
@nicjar this was suggested by you in one of the contentathons. Do you have any resources and materials that we can use to proceed with this page? (Copying @lauportell for information)

**Comment by froggypaule** [comment]
Hello all!
Writing an 'ethics page' has come back to the fore after the latest WP1 F2F at Padova. I did some preliminary work around how ethics is present/covered in the RDMkit, see https://docs.google.com/document/d/17rmxCz4yiJZr4MztDfj9D1ZT7jZLYUbmmA4dZstyw5M/edit#

and it is my opinion that a page 'ethical compliance' is necessary, if only to clarify the boundaries with human data, GDPR, etc...

Anyway, the conversation is open. I ping here @floradanna  and @nicjar.
