### ISSUE TITLE
Plants genotyping tool assembly page

### ISSUE THREAD

**Issue by DanFaria** [elixir-europe/rdmkit#617]
**What topic do you wish to add?**
A tool assembly page describing the assembly of RDM tools to support plant genotyping data.

**Are there existing pages in the RDMkit website related to the requested page?**
https://rdmkit.elixir-europe.org/plant_sciences.html

**Resources**
Documentation from the FONDUE implementation study.

**Context**
This page request is issued as part of the tool assembly contentathon.

**Comment by korbinib** [comment]
Hi @DanFaria, I kindly wanted to ask what the status of this tool assembly is.

**Comment by DanFaria** [comment]
Hi Korbinian. It's still in progress. Will try to complete it by the end of next week.

**Comment by bedroesb** [comment]
@korbinib  and @DanFaria I think this issue can be closed after #663 and #669 ?
