### ISSUE TITLE
Tool Assembly: Images lifecycle using OMERO as an example

### ISSUE THREAD

**Issue by jburel** [elixir-europe/rdmkit#619]
**What topic do you wish to add?**
Enter an entry in the tool Assembly describing the life cycle of images using OMERO as a possible option to manage data.

**Are there existing pages in the RDMkit website related to the requested page?**
No

**Resources**
To be prepared

**Context**
If this request is coming from a particular project, domain, or use-case please list them below:

Invited by leaders to contribute

**Comment by jburel** [comment]
@korbinib when the template is available, happy to add some information to it

**Comment by korbinib** [comment]
@jburel  The current template can be found here: https://github.com/elixir-europe/rdmkit/blob/master/images/optional_template_infrastructure_tool_assembly.svg

**Comment by korbinib** [comment]
There is also a minimal template for the tool assemblies [here](https://github.com/elixir-europe/rdmkit/blob/master/pages/tool_assembly/TEMPLATE_tool_assembly.md)

I would like to suggest the following sections:
I would like to suggest the following sections:

1.     What is OMERO?
2.     Who is OMERO intended for?
3.     Which task(s) can be solved with OMERO?
4.     optional: Training resources (like e.g. webinar recordings, slides, ...)
5.     Tools

Please add your tools to the [csv](https://github.com/elixir-europe/rdmkit/blob/master/_data/main_tool_and_resource_list.csv)  through git or in this [google sheet](https://docs.google.com/spreadsheets/d/16RESor_qQ_ygI0lQYHR23kbZJUobOWZUbOwhJbLptDE/edit#gid=268211668)

You can also add yourself to the [list of contributors](https://github.com/elixir-europe/rdmkit/blob/master/_data/CONTRIBUTORS.yaml).

We are currently revising the tag/page referencing system (#631) so it might be best to leave this until the end.

**Comment by jburel** [comment]
Thanks, I had several deadlines so I did not have time to focus on it

**Comment by jburel** [comment]
Internal draft done, aim to have PR opened on return from holidays

**Comment by jburel** [comment]
https://github.com/elixir-europe/rdmkit/pull/676

**Comment by korbinib** [comment]
Closed by #676
