### ISSUE TITLE
BioImaging data

### ISSUE THREAD

**Issue by jburel** [elixir-europe/rdmkit#620]
**What topic do you wish to add?**
Add Domain page focusing on Bioimaging data

**Are there existing pages in the RDMkit website related to the requested page?**
No

**Resources**
If there are there resources that could be utilised for writing the new page, please list them below:
Not yet.

**Context**
If this request is coming from a particular project, domain, or use-case please list them below:

Asked by leader to prepare page for the domain

**Comment by korbinib** [comment]
Could it be an idea to use [REMBI](https://doi.org/10.1038/s41592-021-01166-8) as a starting point for the microscopy aspects?

**Comment by jburel** [comment]
@korbinib I think we should be able to open a PR next week. REMBI is mentioned in the doc

**Comment by jburel** [comment]
WIP at https://github.com/jburel/rdmkit/tree/domain

**Comment by jburel** [comment]
@korbinib is there a way to specify more than one tag when using 
```
{% include toollist.html tag="your tag" %}
```
I wanted to use 2 for the page we are working on.

Thanks

**Comment by bedroesb** [comment]
@jburel we used to support this, but during some code refactoring I took it out because it was not used. I could bring this feature back if needed.

**Comment by jburel** [comment]
That will be useful I think
Thanks

**Comment by bedroesb** [comment]
and I remember why, tool lists are automatically listed based on the page_id and we do not make use anymore of the snipped you are referring too.

**Comment by jburel** [comment]
Ok so that means that I can only use one!

**Comment by bedroesb** [comment]
Correct, can you tell me where you got this snippet from? Because I thought I took it everywhere out of the website :)

**Comment by jburel** [comment]
I had a version of master from last week where it was present. I have rebased it now. I will need to update the beginning of the page

**Comment by jburel** [comment]
PR https://github.com/elixir-europe/rdmkit/pull/765
