### ISSUE TITLE
Recommendation in Horizon Europe Program Guide

### ISSUE THREAD

**Issue by korbinib** [elixir-europe/rdmkit#627]
**Description**
https://ec.europa.eu/info/funding-tenders/opportunities/docs/2021-2027/horizon/guidance/programme-guide_horizon_en.pdf recommends the RDMkit. This could be added e.g. in the footer.

**Comment by martin-nc** [comment]
Maybe in the 'About' page as well, and even on the home page?

**Comment by bedroesb** [comment]
@korbinib do you have a sentence in mind to put in the footer? Than I add it.

**Comment by korbinib** [comment]
How about: Recommended in the [Horizon Europe Program Guide](https://ec.europa.eu/info/funding-tenders/opportunities/docs/2021-2027/horizon/guidance/programme-guide_horizon_en.pdf) as the "resource for Data Management guidelines and good practices for the Life Sciences" ?

**Comment by Nazeeefa** [comment]
Where in the guide it is mentioned, what page? sorry, I can't seem to find it.

**Comment by korbinib** [comment]
p. 45
