### ISSUE TITLE
New page -  XNAT-PIC: XNAT for Preclinical Imaging Centers

### ISSUE THREAD

**Issue by szullino** [elixir-europe/rdmkit#633]
**What topic do you wish to add?**
**XNAT for Preclinical Imaging Centers (XNAT-PIC)** has been developed to expand XNAT's basic functionalities to preclinical imaging and consists of:

- **MRI2DICOM**, a Magnetic Resonance Imaging (MRI) converter from ParaVision® (Bruker, Inc. Billerica, MA) file format to DICOM standard

- **XNAT-PIC Uploader** to import multimodal DICOM image datasets to XNAT

- **XNAT-PIC Pipelines** for analysing single or multiple subjects within the same project in XNAT.

**Are there existing pages in the RDMkit website related to the requested page?**
No.

**Resources**
If there are there resources that could be utilised for writing the new page, please list them below:

- [XNAT-PIC](https://github.com/szullino/XNAT-PIC)

- [XNAT-PIC-pipelines](https://github.com/szullino/XNAT-PIC-pipelines)

- [https://arxiv.org/abs/2103.02044](https://arxiv.org/abs/2103.02044)

**Context**
If this request is coming from a particular project, domain, or use-case please list them below:

Invited to contribute to the RDMkit.

**Comment by korbinib** [comment]
Hi @szullino, this looks like a great idea. If you would like to contribute through git, please fork the repo and add your own page based on [this template](: https://github.com/elixir-europe/rdmkit/blob/master/pages/tool_assembly/TEMPLATE_tool_assembly.md) and do a pull request.

I would like to suggest the following sections:

1. What is XNAT-PIC?
2. Who is XNAT-PIC intended for?
3. Which task can be solved with XNAT-PIC?
4. optional: Training resources (like e.g. webinar recordings, slides, ...)
5. tools

Please add your tools to the [csv](https://github.com/elixir-europe/rdmkit/blob/master/_data/main_tool_and_resource_list.csv)  through git or in this [google sheet](https://docs.google.com/spreadsheets/d/16RESor_qQ_ygI0lQYHR23kbZJUobOWZUbOwhJbLptDE/edit#gid=268211668)

We are currently revising the tag/page referencing system (#631) so it might be best to leave this until the end.

**Comment by korbinib** [comment]
In addition to a tool assembly page it might be also interesting to have the consideration on DICOM and metadata for preclinical imaging described in a [domain page](https://github.com/elixir-europe/rdmkit/blob/master/pages/your_domain/TEMPLATE_your_domain.md)
