### ISSUE TITLE
Linking the RDM toolkit to specific FAIR Cookbook recipes: seeking advice

### ISSUE THREAD

**Issue by proccaserra** [elixir-europe/rdmkit#683]
**Description**
Hi RDMkit!

As FAIRplus/FAIR cookbook dev are trying to link FAIR cookbook recipes with the RDM toolkit, we are seeking advise on how to go about it.

Currently RDM toolkit annotation with tools or resources can be made using the following syntax:

 {% include toollist.html tag="identifiers" %}

as found for instance in : https://github.com/elixir-europe/rdmkit/blob/master/pages/your_problem/identifiers.md

The FAIRcookbook is already identified as a resource from the following list:
https://docs.google.com/spreadsheets/d/16RESor_qQ_ygI0lQYHR23kbZJUobOWZUbOwhJbLptDE/edit#gid=268211668

I would like to link specific RDM toolkit pages to specific FAIR cookbook recipes (not just a link to the FAIR cookbook).
So are you OK if I add all the individual recipe links to the gsheet you maintain, use the relevant RDMkit tags and then send you PRs when done ?

One more thing: is it possible to request new tags?

Many thanks!
Phil

**Comment by bedroesb** [comment]
@proccaserra WHat do you think of my proposal in #717 ?
