### ISSUE TITLE
Add "Ready for BioData Management?" program to Tools and Resources list

### ISSUE THREAD

**Issue by BioDataAdmin** [elixir-europe/rdmkit#728]
**Description**
It could be interesting to add the "Ready for BioData Management?" program to the Tools and Resources list. 
Below, I leave a suggestion on how it might appear in the RDMkit page:

Description: Capacity building program in data management for the life sciences to empower researchers and institutions in managing their data more effectively and efficiently.

Related pages: Data management plans; researcher

Registry: TeSS

Website page:
http://ready4biodatamanagement.biodata.pt/

**Comment by bedroesb** [comment]
Hello @BioDataAdmin, does this resource have a Portugal specific audience? I ask this since we are planning on restructuring country specific tools to be bundled in a country specific page.

**Comment by BioDataAdmin** [comment]
Good morning, 

 

This course is built for researchers, lab managers, PhD and Master students but it can also be applied to other science professionals.

 

Thank you!

 

Best regards,

Sofia Oliveira

Project Manager | Node Coordinator

BioData.pt | ELIXIR-PT

Instituto Gulbenkian de Ciência 

Rua da Quinta Grande 6, 2780-156 Oeiras, Portugal

Tel: +351 916 680 002

 

 

 

Hello @BioDataAdmin, does this resource have a Portugal specific audience? I ask this since we are planning on restructuring country specific tools to be bundled in a country specific page.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bedroesb** [comment]
Hey @BioDataAdmin ,

I see that other biodata.pt resources are added to the [national resource page of Portugal](https://rdmkit.elixir-europe.org/pt_national_resources.html). Should this one also be added to this page?
