### ISSUE TITLE
Additional audience: collaborators

### ISSUE THREAD

**Issue by korbinib** [elixir-europe/rdmkit#748]
For tool assemblies with a specific audience of users from one country and their (international) collaborators, the country flag might be perceived as too narrow. 'ALL' + Countryflag might be too wide. Adding a ' collaborators' tag might help.

**Comment by bedroesb** [comment]
I don't 100% understand how this would visually look like?

**Comment by Nazeeefa** [comment]
I would suggest again: remove Audience and just keep Affiliations. It says in description already, for example “for researchers in Finland/Norway” and that’s sufficient to mention what audience it is intended for. You could replace it with "for researchers and their collaborators in Finland/Norway"

**Comment by bedroesb** [comment]
I am ok with leaving out audience and to make it clear in the description. Or there other opinions?
