### ISSUE TITLE
Show update dates in pages

### ISSUE THREAD

**Issue by floradanna** [elixir-europe/rdmkit#766]
**Description**
Show update dates in pages.

**Comment by bedroesb** [comment]
Just looked into this. Since GithHub does not allow external plugins, this is only possible if you keep track of this date in the metadata. Which I think is cumbersome...

**Comment by bedroesb** [comment]
We could use systems that deploy the website for us instead of github pages like @martin-nc discovered : https://github.com/jeffreytse/jekyll-deploy-action

I am not in favor of this because it adds complexity and it is not as easy to deploy something on your own fork from a specific branch

**Comment by bedroesb** [comment]
this is covered in #767
