### ISSUE TITLE
pt_resources page

### ISSUE THREAD

**Issue by BioDataAdmin** [elixir-europe/rdmkit#796]
**What topic do you wish to add?**
I would like to add the national resources page for portugal
**Are there existing pages in the RDMkit website related to the requested page?**
No

**Context**
This was proposed in the context of a Converge WP1 meeting

Following the template, our suggestion of page is:

---

title: Portugal
search_exclude: true
country_code: PT
contributors: [Jorge Oliveira]
coordinators: [Ana Portugal Melo]

related_pages: 
  tool_assembly: []

training:
  - name: Training in TeSS
    registry: TeSS
    registry_url: https://tess.elixir-europe.org
    url: https://tess.elixir-europe.org/materials?node=Portugal
  - name: Ready for BioData.pt Data Management?
    registry: R4BDM
    registry_url: http://ready4biodatamanagement.biodata.pt/
    url: http://ready4biodatamanagement.biodata.pt/

resources:
  - name: BioData.pt Service Hub
    Description: BioData.pt Service Hub includes several data management resources, tools and services available for researchers in Life Sciences.
    how_to_access: 
    related_pages:
      tool_assembly: []
      domain: []
      your_role: [researcher, data manager]
      your_tasks: [data analysis, storage]
    Url: http://services.biodata.pt/
- name: BioData.pt Data Management Portal (DMPortal)
    Description:This instance of DataVerse is provided by the BioData.pt. We can help you write and maintain data management plans for your research.
instance_of: DATAVERSE
    how_to_access: 
    related_pages:
      tool_assembly: []
      domain: []
      your_role: [researcher, data manager, data steward]
      your_tasks: [data management, storage]
    Url: https://dmportal.biodata.pt/
- name: BioData.pt Data Stewardship Wizard
    Description: Local instance of Data Stewardship Wizard. You can use this tool to create your own Data Management Plans.
instance_of: Data Stewardship Wizard
    how_to_access: 
    related_pages:
      tool_assembly: []
      domain: []
      your_role: [researcher, data manager, data steward]
      your_tasks: [data management, data management plans]
    Url: https://biodata-pt.ds-wizard.org/

---

## Introduction 
An overview of data management services provided by ELIXIR Portugal / BioData.pt can be found on the BioData.pt Website. 

## Institutional policies on research data in Portugal
[Centre of Marine Sciences (CCMAR)](https://ccmar.ualg.pt/en/page/open-science-and-data-management)

## Funders

* [Fundação para a Ciência e Tecnologia (FCT)](https://www.fct.pt/)

**Comment by floradanna** [comment]
Hi, Bert created a page for Portugal. You can find it here: https://github.com/elixir-europe/rdmkit/blob/master/pages/national_resources/pt_national_resources.md

**Comment by BioDataAdmin** [comment]
Hi,

 

Incredible! Thank you so much.

 

Best,

Sofia Oliveira

Project Manager | Node Coordinator

BioData.pt | ELIXIR-PT

Instituto Gulbenkian de Ciência 

Rua da Quinta Grande 6, 2780-156 Oeiras, Portugal

Tel: +351 916 680 002

 

 

Yes, the page is visible here: https://rdmkit.elixir-europe.org/pt_national_resources.html

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
