### ISSUE TITLE
National resources page - Germany

### ISSUE THREAD

**Issue by wittigue** [elixir-europe/rdmkit#797]
**What topic do you wish to add?**
Please provide a brief description.

**Are there existing pages in the RDMkit website related to the requested page?**

**Resources**
If there are there resources that could be utilised for writing the new page, please list them below:

**Context**
If this request is coming from a particular project, domain, or use-case please list them below:

**Comment by bedroesb** [comment]
hey @wittigue I made a page where you can add your national resources: https://rdmkit.elixir-europe.org/de_national_resources.html

If you are happy with the content, delete the `search_exclude` line in the metadata
