### ISSUE TITLE
National resources -> Show pages in homepage broken

### ISSUE THREAD

**Issue by nsoranzo** [elixir-europe/rdmkit#800]
**Describe the bug**
Something's wrong with the "Show pages" button in the "National resources" tile: when clicked, no list of page links appears, while the "Show pages" button in all other tiles works fine.

**To Reproduce**
1. Go to the RDMkit homepage
2. Click on the "Show pages" button in the "National resources" tile
3. The button label changes to "Hide pages", but no list of page links appears.

**Expected behavior**
Clicking on "National resources" on the left menu brings to the national_resources.html pages, which has links for (currently) 6 countries, so I'd expect the same elements to appear when clicking "Show pages".

**Screenshots**
![image](https://user-images.githubusercontent.com/4924623/149384904-1db5283c-42b3-4769-b2c7-3fd96e31b3d7.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 95

**Comment by bedroesb** [comment]
Good catch! I fixed it, thank you for reporting @nsoranzo
