### ISSUE TITLE
Updating national resources page Finland

### ISSUE THREAD

**Issue by bedroesb** [elixir-europe/rdmkit#814]
During the biohackathon we finalized how we will handle country specific tools. Some of these country specific tools were moved to their designated country pages, including Finland. These pages now exist but don't have any content. 

The page can be found at https://rdmkit.elixir-europe.org/fi_resources.html
and edited using the pencil icon.

**Comment by siirif** [comment]
I just did a pull request. Next I need to add the tools to the table and then I would need to make a more resources box to the end, but I don't know how to do it. 

This should be added to a more info box to the end of the page:

**More information**
Training in TESS https://tess.elixir-europe.org/search?q=csc
Training and Events Calendar https://www.csc.fi/en/training
CSC YouTube https://www.youtube.com/c/CscFi/playlists
Search for information on research in Finland https://research.fi/en/ 
CSC Tool Assembly:  https://rdmkit.elixir-europe.org/csc_assembly.html

**Comment by siirif** [comment]
Also I'm sorry  I cannot make the table for the resources / tools. If someone can help, it would be super!

Our resources: 
resources:
  - name: Chipster
    description: Chipster is a user-friendly analysis software for high-throughput data such as RNA-seq and single cell RNA-seq. It contains analysis tools and a large reference genome collection.
    how_to_access: 
    related_pages:
      tool_assembly: [CSC]
      your_role: [researcher, IT support]
      your_tasks: [data analysis]
    url: https://chipster.csc.fi/
  - name: DMPTuuli
    description: Data management planning tool (Finland)
    instance_of: DMPRoadmap
    how_to_access: 
    related_pages:
      tool_assembly: [CSC]
      your_role: [researcher, data manager]
      your_tasks: [DMP]
    url: https://www.dmptuuli.fi/
- name: Fairdata.fi
    description: With the Fairdata Services you can store, share and publish your research data with easy-to-use web tools.
    instance_of: 
    how_to_access: 
    related_pages:
      tool_assembly: [CSC]
      your_role: [researcher, data manager]
      your_tasks: [storage, data_publication, existing_data]
    url: https://research.csc.fi/-/fairdata-services
- name: Federated EGA Finland
    description: FEGA allows you to store and shaare sensitive data in Finland in a way that fulfils all the requirements of the General Data Protection Regulation (GDPR).
    instance_of: 
    how_to_access: 
    related_pages:
      tool_assembly: [CSC]
      your_role: [researcher, data manager]
      your_tasks: [sensitive_data, data_publication, existing_data]
      your_domain: [human_data]
      url: https://research.csc.fi/-/fega
- name: Findata
    description: The Health and Social Data Permit Authority. Findata offers services and enables secure and efficient utilisation of data materials containing health and social data.
    instance_of: 
    how_to_access: 
    related_pages:
      tool_assembly: [CSC]
      your_role: [researcher, data manager]
      your_tasks: [sensitive_data, existing_data]
      your_domain: [human_data]
      url: https://findata.fi/en/
- name: Fingenious
    description: Finnish Biobank Cooperative (FINBB) connects researchers to Finnish biomedical research. Via Fingenious® services the researcher can connect to all Finnish public bio banks.
    instance_of: 
    how_to_access: 
    related_pages:
      tool_assembly: [CSC]
      your_role: [researcher, data manager]
      your_tasks: [sensitive_data]
      your_domain: [human_data]
      url: https://site.fingenious.fi/en/
- name: Sensitive Data Services for Research
    description: CSC Sensitive Data Services for Research are designed to support secure sensitive data management through web-user interfaces accessible from the user's own computer
    instance_of: 
    how_to_access: 
    related_pages:
      tool_assembly: [CSC]
      your_role: [researcher, data manager]
      your_tasks: [sensitive_data, data_analysis, data_storage, data_publication]
      your_domain: [human_data]
      url: https://research.csc.fi/sensitive-data-services-for-research
- name: High performance computing
    description: CSC Supercomputers Puhti, Mahti and LUMI performance ranges from medium scale simulations to one of the most competitive supercomputers in the world.
    instance_of: 
    how_to_access: 
    related_pages:
      tool_assembly: [CSC]
      your_role: [researcher, data manager]
      your_tasks: [data_analysis]
      url: https://research.csc.fi/computing#high-performance-computing
- name: Cloud computing
    description: CSC offers a variety of cloud computing services: the Pouta IaaS services and the Rahti container cloud service.
    instance_of: 
    how_to_access: 
    related_pages:
      tool_assembly: [CSC]
      your_role: [researcher, data manager]
      your_tasks: [data_analysis]
      url: https://research.csc.fi/computing#cloud-computing
