### ISSUE TITLE
Proposal: Add links to national DM policies to National resources pages

### ISSUE THREAD

**Issue by nsoranzo** [elixir-europe/rdmkit#820]
**Description**
In the latest ELIXIR Technical Coordinators meeting, Andrew Smith (Head of External Relations, ELIXIR) told us that the Hub would like to better track the existing data management policies and guidance of the national funders (and make sure these reference ELIXIR resources). Some Tech Coordinators mentioned that national policies are already linked in a few "National resources" pages, so we proposed that these pages should become the "official" place where we these lists are maintained.
I see there is already a [template for the National resources](https://github.com/elixir-europe/rdmkit/blob/master/pages/national_resources/TEMPLATE_national_resources.md), so I was wondering if that could be made a bit more specific in order to accomplish this goal?
Maybe this should be coordinated between the Editorial Board and the Hub, but I wanted to also track it as a GitHub issue.

**Comment by smza** [comment]
The RDMkit NR page lists the DM guidelines from National funders  as well as other regulatory bodies. This information can feed into the tracker that the Hub is looking for BUT the RDMkit per se will not maintain lists or track  such efforts.

**Comment by bedroesb** [comment]
@nsoranzo thanks for bringing this up!
