### ISSUE TITLE
inform page authors about changes

### ISSUE THREAD

**Issue by floradanna** [elixir-europe/rdmkit#840]
**Description**
Currently, an author/contributor of a page does not get notified when changes in that page are made. So, people could end up being authors of content that they have never seen and are not aware of.

How could we solve this issue?

Ideally, every author/contributor that has the name on a specific page should be notified when that page is edited.

**Comment by floradanna** [comment]
Currently, in RDMkit, contributors are considered contributors to RDMkit and not authors of specific content. So, maybe it is not important that contributors get notified when changes to the content are made.

Is this clear enough in our "Contribute" section?

**Comment by bedroesb** [comment]
@floradanna do you make this clear in our contribute section, if not?

**Comment by floradanna** [comment]
I am not sure what we are allowed to write exactly. So, here there is a draft. Feedback are needed.

**Ownership of content**
Contributors and editors are NOT the owner of RDMkit content. 
_What about RDMkit since we have CC-BY licence on content?_

If you create content in a RDMkit page, others can make changes at any time without notifying you. 
Someone else’s changes should not be undone without good reasons. 
To see who made specific changes on GitHub, please check the history of the GitHub page or related issues.

RDMkit content is written collaboratively by different communities and should reflect large consensus on a topic. 
RDMkit editors make an effort to take into account legitimate concerns and different point of views of all contributors during the publication process.

**Comment by martin-nc** [comment]
What about something like:

> ### Ownership of content
> No single contributor or editor owns the content of the site, or has the right to dictate what the content should be. The content on the RDMkit is a community effort, with many people contributing. Decisions are driven by consensus among the contributors and editors. 
> 
> The content is periodically updated, which means that if you create content in an RDMkit page, others can change the content without notifying you. However, the RDMkit editors ensure that content is only modified for good reasons. 
> 
> The RDMkit editors try to ensure:
>
> -  the legitimate concerns and different point of views of all contributors are accommodated;
> -  the content is up to date;
> -  the content reflects the most popular consensus on any given topic;
> -  the content conforms to the [site style guide](https://rdmkit.elixir-europe.org/style_guide).
>
> If you find any content unsatisfactory, please feel free to [create an issue](https://github.com/elixir-europe/rdmkit/issues/new/choose) about it.

This might be of use: https://en.wikipedia.org/wiki/Wikipedia:Ownership_of_content. Maybe I've talked too much about editors, but I think we should reserve the right to have the ultimate say, though of course we hope that will reflect popular consensus. Also we perhaps need to explain what the "good reasons" are.

I didn't mention CC-BY because I'm not sure if it's relevant. Doesn't that let you chop content around anyway, as long as you keep a credit and record of modification (I guess that would be the page history)?

**Comment by floradanna** [comment]
Thanks Martin.
I indeed took inspiration from the same Wikipedia page, although I think that we cannot do exactly the same because we are a bit different (we explicitly list contributors, we have editorial board, we put CC-BY licence on content to give credit to RDMkit...). I also was hoping to keep it a bit simpler. I am also not sure if we should mention the HISTORY.

I mostly agree with your suggestion, except on the 4 bullet points about editors duties. I would only write that 
`"The RDMkit editors try to ensure that the legitimate concerns and different point of views of all contributors are accommodated and that the content reflects the most popular consensus on any given topic"`

I don't think editors can ensure that the content is up to date, the communities should take care of that. We might just encourage communities to review the content from time to time.

About the style guide and other guidelines, I was thinking to have a dedicated paragraph for that and/or make a "contributors checklist".

**Comment by martin-nc** [comment]
That's fine to me. I might put a comma after "accommodated" in your sentence, just to break the long sentence up:

> The RDMkit editors try to ensure that the legitimate concerns and different point of views of all contributors are accommodated, and that the content reflects the most popular consensus on any given topic.

**Comment by floradanna** [comment]
Final text:

**Ownership of content**

No single contributor or editor owns the content of the site, or has the right to dictate what the content should be. The content on the RDMkit is a community effort, with many people contributing. Decisions are driven by consensus among the contributors and editors.

The content is periodically updated, which means that if you create content in an RDMkit page, others can change the content without notifying you. However, the RDMkit editors ensure that content is only modified for good reasons. The RDMkit editors try to ensure that the legitimate concerns and different point of views of all contributors are accommodated, and that the content reflects the most popular consensus on any given topic.

If you find any content unsatisfactory, please feel free to [create an issue](https://github.com/elixir-europe/rdmkit/issues/new/choose) about it.

**Comment by bedroesb** [comment]
@floradanna where will this be added? In our Code of Conduct or in the contribute landing page?

**Comment by floradanna** [comment]
I would say to "contribute" landing page, if nobody objects. It would need some rewriting of the existing content.

**Comment by bedroesb** [comment]
Good for me, do you open a PR?
