### ISSUE TITLE
Adding coordinators attribute to other templates

### ISSUE THREAD

**Issue by bedroesb** [elixir-europe/rdmkit#841]
Do we want to select a coordinator for every page on RDMkit?

**Comment by bedroesb** [comment]
Coordinator role only for country pages, but we have to make sure that each page has at least one contributor listed so we can contact them if we do a curation/contentathon session. Task for @floradanna

**Comment by floradanna** [comment]
Contact contributors of the following pages and ask for contact info to be added to the yaml file:
- https://rdmkit.elixir-europe.org/marine_metagenomics
- https://rdmkit.elixir-europe.org/covid19_data_portal
- https://rdmkit.elixir-europe.org/ifb_assembly
- https://rdmkit.elixir-europe.org/ee_resources
- https://rdmkit.elixir-europe.org/pt_resources

Structural bioinformatics page uses "coordinator attribute" in metadata: https://rdmkit.elixir-europe.org/structural_bioinformatics. Keep or delete?

**Comment by bedroesb** [comment]
You can throw it out

**Comment by floradanna** [comment]
@elixir-europe/rdmkit-editors I will contact some of the contributors of the pages listed above on behalf of RDMkit editors by tomorrow afternoon. If you don't agree or you would like to discuss something further, please let me know before tomorrow afternoon.

**Comment by bedroesb** [comment]
@floradanna with #920 can this issue be closed?

**Comment by floradanna** [comment]
I would prefer to keep it open until the contributors of the last page (covid19 data portal) add also their info. So I don't forget.

**Comment by bedroesb** [comment]
oh ok, good. Thanks for keeping track!
