### ISSUE TITLE
Consistency for ToC

### ISSUE THREAD

**Issue by floradanna** [elixir-europe/rdmkit#859]
**Description**
Although most of the pages have a "Table of content", few pages don't. Is there a reason or a rational for this? If yes, is it explained somewhere?
For instance, "About" page has a ToC, while "Contribute" doesn't not. Within "Contribute" section, most pages have ToC except "Copyrights guidelines" and "Git way (advanced)".

**Comment by bedroesb** [comment]
I am ok in always activating it from the moment there are at least two H2 items
