### ISSUE TITLE
News & Events page

### ISSUE THREAD

**Issue by Nazeeefa** [elixir-europe/rdmkit#860]
Currently, we have Events page mentioned in 'About' section. 

In RDMkit editors meeting today, we have discussed to:

- [ ] Add 'News & Events' in top menu
- [ ] Add three side sub-sections: News ("What's New?"), Upcoming Events, and Past Events.
- [ ] Add short description for 'What's New?' sub-section, to help reader make distinction between 'News' and 'Events'.

**Comment by bedroesb** [comment]
I thought it would have been just news in the top navigation :)

**Comment by Nazeeefa** [comment]
That's also fine to use just News :) As we discussed in the meeting, News and Events is something most websites appear to use so it's a known/common thing.

Regarding sub-sections for events, those were suggested because the page I initially saw had links to 'Upcoming Events' and 'Past Events' (the one where we noticed the JS/- bug 🐞). 

Also, in my calendar, there are two upcoming RDMkit related events: RDMkit/DSW session on Data Reuse, and RDMkit seminar at NIH. About past events, it's important for us editorial team to keep a note of them but I don't fully understand the purpose of displaying them on website.

**Comment by bedroesb** [comment]
I agree with you that we should decide on what we see as an event. Until now it where things that we organized ourselves where people can participate to, not talks where RDMkit is mentioned. But I also have difficulties placing the presentations on the website on a good location.

**Comment by bedroesb** [comment]
@Nazeeefa I added a line on https://rdmkit.elixir-europe.org/outreach.html and https://rdmkit.elixir-europe.org/media_kit.html to clarify more these things. What do you think?

**Comment by bedroesb** [comment]
Based on feedback in #865 and clarifications in #884 I will close this issue.

**Comment by Nazeeefa** [comment]
Thank you, @bedroesb! I like the text you put, and thought I'd share my suggestions anyway - feel free to make changes you like:

For the Outreach page https://rdmkit.elixir-europe.org/outreach.html]
- It would may be helpful if presentations are listed in reverse order i.e. recent one first.
-  Text suggestion:
> We are, since the beginning, actively spreading the word about RDMkit making sure it reaches a wider audience across the globe. On this page, we keep a track of where RDMkit has been presented so far and the relevant links. If you would like to showcase your talk/slides here, let us know <contact info?>

For the Media Kit page https://rdmkit.elixir-europe.org/media_kit.html

_This page provides materials that you can use for the dissemination of the RDMkit and when re-using the information provided on the website. The logo and images listed here are licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/), just like the rest of the content on RDMkit. This means that you can use them, as long as you give attribution to RDMkit. For images and logo, we recommend you to use the svg format since this will preserve the image quality better._
