### ISSUE TITLE
Checklist for editors

### ISSUE THREAD

**Issue by floradanna** [elixir-europe/rdmkit#871]
**What topic do you wish to add?**
Checklist for editors. What to check before merging a pull request.

**Are there existing pages in the RDMkit website related to the requested page?**
Contribute section and Editorial board guide. The checklist could be placed in a separated page in the Contribute side menu or within the Editorial board guide page.

**Context**
This request is coming from rdmkit editors.

**First draft**

### Before merging a pull request, the editor must check that
1. The page layout in preview looks correct.
2. The `page_id` is unique ([Website overview](https://rdmkit.elixir-europe.org/website_overview.html)).
3. The new page is linked to the appropriate sidebar menu ([sidebars](https://github.com/elixir-europe/rdmkit/tree/master/_data/sidebars)).
4. The contributors' names are listed in [CONTRIBUTORS.yaml](https://github.com/elixir-europe/rdmkit/blob/master/_data/CONTRIBUTORS.yaml).
5. All metadata fields in the page are correctly filled in (see the [Editorial board guide](https://rdmkit.elixir-europe.org/editorial_board_guide.html)).
* Common metadata fields are:
  * `title`
   * `page_id` or `country_code`
   * `contributors`
   * `related_pages` ([Related pages](https://rdmkit.elixir-europe.org/editorial_board_guide.html#related-pages))
   * `training`
   * `search_exclude` must be deleted
* Task-specific metadata fields are:
    * `description`
* Tool assembly-specific metadata fields are:
     * `description`
     * `affiliation`
* National resources-specific metadata fields are:
     * `coordinators`(they must be listed as `contributors` as well)
     * `resources`
6. Items in the "[all tools and resources spreadsheet](https://docs.google.com/spreadsheets/d/16RESor_qQ_ygI0lQYHR23kbZJUobOWZUbOwhJbLptDE/edit#gid=268211668)" are tagged with already existing (merged) `page_id` from:
* Role
* Domain
* Tasks
* Tool assembly
7. The content is conform to RDMkit scope and [style](https://rdmkit.elixir-europe.org/style_guide.html).
8. The layout is conform to RDMkit templates.
9. The contributors implemented the requested changes.
10. Related news are added to the news/event page.
11. The contributors are thanked for their effort and informed about the publication of their content.
12. The PR is linked to related issues and can be merged in main branch with no conflicts.

**Comment by bedroesb** [comment]
Some others that popped into my mind:

- Are coordinators also listed contributors? If not, they will not appear
- is the search_exclude attribute gone in the metadata?
- Is the related issues linked to this PR

**Comment by floradanna** [comment]
Thanks! I would avoid explaining how to do things in the checklist though, and make sure that all "how to" info are in the editorial board guide.
> * Are coordinators also listed contributors? If not, they will not appear

This should go to the editorial board guide. I can add it.

> * is the search_exclude attribute gone in the metadata?

This should go to the editorial board guide. I can add it.

> * Is the related issue linked to this PR

This is already explained in the guide.

**Comment by bedroesb** [comment]
Most of what you list is already explained in the editorial guide, I think we should discuss how to present this list

**Comment by floradanna** [comment]
I added your suggestions. I just would like to keep the checklist as short as possible to avoid having another long guide.

**Comment by floradanna** [comment]
### Before approving or merging a pull request, the editor must check that
1. The page layout in preview looks correct.
3. The new page is linked to the appropriate sidebar menu ([sidebars](https://github.com/elixir-europe/rdmkit/tree/master/_data/sidebars)).
4. The contributors' names are listed in [CONTRIBUTORS.yaml](https://github.com/elixir-europe/rdmkit/blob/master/_data/CONTRIBUTORS.yaml).
5. All relevant metadata fields in a specific page are correctly filled in (see the [Editorial board guide](https://rdmkit.elixir-europe.org/editorial_board_guide.html) and the [Markdown cheatsheet](https://rdmkit.elixir-europe.org/markdown_cheat_sheet.html)). Some critical ones are listed below.
   * unique `page_id` ([Website overview](https://rdmkit.elixir-europe.org/website_overview.html)).
   * `contributors`
   * `related_pages` ([Related pages](https://rdmkit.elixir-europe.org/editorial_board_guide.html#related-pages))
   * `training`
   * `search_exclude` must be deleted
   * `description`
   * `affiliation`
   * `coordinators`(they must be listed as `contributors` as well)
   * `resources`
6. Items in the "[all tools and resources spreadsheet](https://docs.google.com/spreadsheets/d/16RESor_qQ_ygI0lQYHR23kbZJUobOWZUbOwhJbLptDE/edit#gid=268211668)" are tagged with already existing (merged) `page_id` from "Role, Domain, Tasks, Tool assembly" and that Bert has been informed of changes.
7. The content is conform to RDMkit scope, [style](https://rdmkit.elixir-europe.org/style_guide.html) and templates.
9. The contributors implemented the requested changes.
10. News items are added to the news/event page (rdmkit/_data/news.yml).
11. The contributors are thanked for their effort and informed about the publication of their content.
12. The PR is linked to related issues and can be merged in main branch with no conflicts.

**Comment by martin-nc** [comment]
The list looks good to me. I just had a related thought, to do with point 6 ("style"). It's easy when you're busy to let text through text that's too long or convoluted. This all accumulates over time. I wonder if it's an idea to have a review of content after a certain time period, like 6 months or a year. This will allow us to stand back and get an overview of the pages and see if they can be be shorter, more digestible, or presented in a more user-friendly way. Again, it's not directly related to the checklist, but just an idea in passing.

**Comment by lauportell** [comment]
It looks good to me as well 👍 
Thank you Flora for putting all this together!
