### ISSUE TITLE
Data life cycle: Sharing - discipline-specific repositories

### ISSUE THREAD

**Issue by jennyostrop** [elixir-europe/rdmkit#876]
I suggest to include links/more explanation to how to find a suitable discipline-specific repository e.g. ELIXIR repositories. I work as support personnel and receive regularly requests from researchers who are not familiar with the respective repositories for their data.

**Comment by floradanna** [comment]
Hi, thank you for your valuable feedback.

Is the information about "how one should proceed to select a research data repository", that you were looking for, present in this page: https://rdmkit.elixir-europe.org/data_publication.html#which-repository-should-you-use-to-publish-your-data ?

How to deposit a dataset depends on the specific repository, but we give some guidance here: https://rdmkit.elixir-europe.org/data_publication.html#how-do-you-prepare-your-data-for-publication-in-data-repositories.

Could you please answer the following questions? It would really help improving the website. 
1. What did you expect to find when clicking on "Share" in the data life cycle?
2. What would have made it easier to find the "Related page" called "Data publication" in Your tasks section?
3. What keywords would you use to search for information about how to select data repositories?

Thank you very much for your help. It is really valuable to RDMkit.

**Comment by jennyostrop** [comment]
Hi,

Yes, data publication covers the aspects I was looking for, but it is very easy to oversee this page in the long list of “Your tasks”.
To answer your questions:

1. What did you expect to find when clicking on "Share" in the data life cycle?

My aim was to provide a researcher with a “help me, a journal requires data deposition, what should I do”-request and little pre-existing knowledge with a link to domain-specific information. Using the research data life cycle appears natural here and searching for suitable information implies skimming over pages rather than thorough reading and following links.
I have a life science background and can thus directly recommend databases, but colleagues might not and might use the RDM kit to find recommendations – adding a role support staff (with knowledge about RDM but possibly without disciplinary knowledge) with site map-type information could be very useful.
2. What would have made it easier to find the "Related page" called "Data publication" in Your tasks section?

In-text link to please find detailed information under … under the bullet-point “Share and publish your data in professional deposition databases that provide the appropriate access type and licence: […]”
Optionally, a section/box at the top of the page with “the following tasks may be relevant at this life cycle stage” and links.
3. What keywords would you use to search for information about how to select data repositories?
Not sure if I understand your question, do you mean in the RDMkit (here, I will not necessarily search as I would expect the information to be present connected to a stage in the data life cycle) or in general? For the latter, I would search for method (microscopy, flow cytometry,…) and repository/research data archive/deposition database/…

Kind regards,
Jenny

**Comment by floradanna** [comment]
Thank you very much for taking the time to answer these questions. Your feedback is highly valuable and will help improving RDMkit.

You, your colleagues or researchers are very welcome to contact us at any time to give feedback about RDMkit.

**Comment by bedroesb** [comment]
In a continuous attempt to improve the user experience on our website, I am trying out a new design of the related pages so they should be more prominent + have a common style related to the tiles that we have in the section landing pages. 

Do you think the tiles in this [Sharing](https://bedroesb.github.io/rdmkit/sharing) page are more clear? @jennyostrop

**Comment by jennyostrop** [comment]
You are referring to the "Related pages" section at the bottom of the page? I think they look good (once I have scrolled all the way down). Wondering if this information would be more prominent in the overview ("On this page") if called "Related topics"?

Another thought: would it be possible to tag the different tasks with one or several stages in the Data life cycle?

**Comment by bedroesb** [comment]
I personally always liked the idea of calling it "What to read next" or "Read next"

**Comment by jennyostrop** [comment]
@bedroesb I was imagining that each task could have one or several little, color-coded tags with the relevant life cycle stage(s) under the heading and on the tasks overview page.
Not quite sure if this would cause more confusion/even more information overload or help to crosslink the different parts.

As for "Read next": In the role of someone who reads up on a topic I like it, while I would find less helpful in the role of trying to navigate to the relevant information as fast as possible.
