### ISSUE TITLE
biomolecular_simulation_data domain page: list of contributors missing

### ISSUE THREAD

**Issue by bianchini88** [elixir-europe/rdmkit#880]
**Link to the page of interest**
https://rdmkit.elixir-europe.org/biomolecular_simulation_data.html

**Describe what you would change to the page**
The list of contributors is somehow missing on this page. Note that a DSW/RDMkit integration event is planned for this topic, 
so we want to make sure we involve the right people/community.  Additional metadata (related pages) would also help improve the page.

**Comment by floradanna** [comment]
Thanks for reporting this. Based on commits history, I added Karel as contributor.
@KarelBerka could you please check if these related pages are correct and add the names of additional contributors, if needed?
