### ISSUE TITLE
Issue on page: All tools and resources

### ISSUE THREAD

**Issue by wouteraddink** [elixir-europe/rdmkit#902]
I would like to report an issue on the All tools and resources page at `/all_tools_and_resources`. Description of the issue:

Mix-up between ABCD and AbCD: the description is about ABCD ([Access to Biological Collection Data Schema (ABCD)](https://www.tdwg.org/standards/abcd/))  but tool info points to AbCD: https://yunliweb.its.unc.edu/AbCD.html

**Comment by bedroesb** [comment]
Good catch! This link was made with bio.tools automatically since the name matched perfectly, but off course this is wrong. A fix is on the way!

**Comment by bedroesb** [comment]
thanks from opening this issue!
