### ISSUE TITLE
broken link to MIGS/MIMS 

### ISSUE THREAD

**Issue by bianchini88** [elixir-europe/rdmkit#908]
**Link to the page of interest**
https://rdmkit.elixir-europe.org/all_tools_and_resources
https://rdmkit.elixir-europe.org/marine_metagenomics#managing-marine-metagenomic-metadata

**Describe what you would change to the page**
The link http://wiki.gensc.org/index.php?title=MIGS/MIMS seems to be broken.
Note that the same link is also listed as "homepage" on the FAIRsharing entry https://fairsharing.org/FAIRsharing.va1hck

**Comment by bedroesb** [comment]
is it me or is the link still working but the site is broken?

**Comment by bedroesb** [comment]
oh you linked the correct one. Sorry. That one does not look nice either :D

**Comment by bianchini88** [comment]
Yes, sorry, that's how I should have phrased it.

**Comment by bedroesb** [comment]
We should take it out of the tools list, this website is clearly not maintained anymore

**Comment by bianchini88** [comment]
MIMS and MIGS are part of MIxS. On their website https://gensc.org/mixs/
they just link the publications and not other resources.

**Comment by bianchini88** [comment]
I had a quick chat with Korbinian. He suggests NOT taking the tool out of the list as it has domain-specific relevance. Link-wise, he suggests just using https://gensc.org/mixs/ also for the MIGS/MIMS entry.
