### ISSUE TITLE
Incorporate 'Your role' section

### ISSUE THREAD

**Issue by martin-nc** [elixir-europe/rdmkit#94]
I find it odd that the pages in 'Your role' talk about fictional characters (e.g. Janet Brown). Reading the page, I feel they're talking about someone else's problems, and not addressing mine. 

Maybe we should remove 'My background' and change 'Common data issues I encounter' to 'Common data issues'. That way the information is more about the role than about one person, and people can relate to it easier. The fictional persona information is useful for internal consumption, to help us understand users better, but I don't know if it's useful on the website. 

What do you think?

P.S. Sorry if this has been through lots of discussion already and I missed it!

**Comment by pinarpink** [comment]
In the break out group we discussed this. An example new page will be written. Once this is reviewed in the break out (Big chance that we delete the biography and name) @MijkeJetten is the contact.

**Comment by martin-nc** [comment]
@MijkeJetten here is the link the the user profiles done in the first hackathon:
https://drive.google.com/drive/folders/1cDn-eHZiTPVZUgtm63rIK_pjRgUToFbo
These are supposed to be the target audience of the site, though I think they should always be open to refinements based on feedback and experience working with the target audience.

At the top level of the hackathon directory there is also this overview, which covers the aims of the site:
https://docs.google.com/document/d/102fbQiaZ63GpL9ZHYLcg1HQmW9CJqTiBi5hJQmzsIos/edit#heading=h.q3rnhv222r1q

The aims are taken from the CONVERGE grant application so they're a bit abstract. Perhaps the 'About us' page could put the goals of the site in a simpler and clearer way!

**Comment by MijkeJetten** [comment]
Mijke will meet with contentathon group again to finalise new content and add to website.
**
Dear Mijke and all,
We had our regular CONVERGE WP3 call today. We reviewed the pages added during the contentathon. "Your role" section did not appear to contain the additions and changes done. If help is needed to get these on the website please let me know.

We also discussed how the "tools table" should be included in the pages and what tag filters should be used. As you may remember, depending on page topics we tag tools and we insert filtered views of tools into pages. We assumed the roles pages will not be including a filtered list of the tools table, and hence tools need not be tagged at this stage with roles. 

@Mijke, we can discuss further in the editors call on 30 October at 10:00 CEST.
regards
Pinar
**

**Comment by floradanna** [comment]
A possible way to solve this issue could be to:
1) Make an ["introduction" page for "your role section"](https://github.com/elixir-europe/rdm-toolkit/issues/156#issuecomment-736721361), where we explain the different [types (or roles) of data steward](https://zenodo.org/record/3490855#.X8aJCi9h35Y).
2) Make sure that the "Common data issues" listed by each "role" are addressed by "Your problem" pages.
3) Tag "your problem" pages with the most appropriate "role".
4) Automatically list "your problem" pages related to a specific "role" (at the bottom of each "your role" page) by using the tag.

In this way, a data steward can easily find the answers to his/her most common DM issues according to his/her role.

**Comment by floradanna** [comment]
This issue has been solved.
