### ISSUE TITLE
Reproducible data analysis

### ISSUE THREAD

**Issue by bedroesb** [elixir-europe/rdmkit#941]
There has been a request to have more content about reproducible data analysis, including the use of workflowhub. We could start with renaming the [first subtitle of the data analysis page](https://bedroesb.github.io/rdmkit/data_analysis#what-are-the-best-practices-for-data-analysis)  to: 

### How to make you analysis reproducible?

This already fits well with the explanation that is put there. 

@supernord what do you feel about this and do you think updating this page would serve the needs?

**Comment by CaroleGoble** [comment]
I wll take this to the WorkflowHub Club

**Comment by floradanna** [comment]
This is also one of the topic that has been selected during the WP1 F2F meeting in Padova to be extended.

[Google doc from WP1.](https://docs.google.com/document/d/1J_p0LbckP7_BKzGRGvuwCNFG4Ej5tmsrsStV_AZMjIo/edit#heading=h.58yb4u5em02r)

Content missing: how do you make your computational workflow findable or how do you share/publish it?
Considerations: ...
Solutions: Galaxy eu or other instances, registration in WorkflowHub, etc

@vergoulis your name is listed in the google doc. Please, contact the editors if you need any help.

**Comment by bedroesb** [comment]
We have have potential content for this in the SIS Containers Project: https://demo.hedgedoc.org/RjJr8Lc8SDWmak2sEg7Dkw
