### ISSUE TITLE
SVGs in tools assembly pages do not make use of the website fonts

### ISSUE THREAD

**Issue by bedroesb** [elixir-europe/rdmkit#953]
**Describe the bug**
Some SVG images don't use the website font

**To Reproduce**
Go to the [NeLS](https://rdmkit.elixir-europe.org/nels_assembly#for-what-can-you-use-the-nels-data-management-tool-assembly) page as example 

**Expected behavior**
I expected to at at least not have a Times New Roman font

**Screenshots**
![Screenshot from 2022-06-30 15-00-15](https://user-images.githubusercontent.com/44875756/176683370-67c85b1d-9574-46ca-93c8-a63f2b2787e6.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Edge, Firefox
 - Version: 102.0.1245.44, 101.0.1 (64-bit)

**Comment by martin-nc** [comment]
@bedroesb The `<img>` tag is used to embed the image, which means the browser will use the system default font (Times) in the SVG, if a font is not embedded in the image.  Perhaps the best thing is the embed the font, or convert the text to outlines. I'm assuming we don't want to use inline SVG here.

Illustrator allows you to embed a font. I don't think Inkscape does, but you can do it here: https://vecta.io/nano.

**Comment by korbinib** [comment]
I hope embedding the font does fix the issue. On a side note: Which figures are subject to the styling guide and which are not?

**Comment by martin-nc** [comment]
I guess we should be consistent with illustrations and keep to brand colours and fonts wherever possible, and standard icons. I'm not sure when there might be exceptions. Possibly we might get inundated with image suggestions and don't have time to make sure they conform to the style guide, but this seems unlikely!
