### ISSUE TITLE
ELIXIR-AAI -> LS Login

### ISSUE THREAD

**Issue by korbinib** [elixir-europe/rdmkit#964]
**Link to the page of interest**
https://rdmkit.elixir-europe.org/

**Describe what you would change to the page**
The RDMkit should reflect the migration from ELIXIR-AAI to LS Login.
This includes:
* Tool Assemblies
* Tools

**Comment by bedroesb** [comment]
@korbinib do you change this or do I have a look? I can have a look in replacing it in the tools table. Do we link to this page? https://lifescience-ri.eu/ls-login/

**Comment by korbinib** [comment]
Will look into the figures. Yes, I guess that's the correct page to link to,

**Comment by korbinib** [comment]
blocked by https://github.com/elixir-europe/rdmkit/pull/1249
