### ISSUE TITLE
Cyprus national page

### ISSUE THREAD

**Issue by floradanna** [elixir-europe/rdmkit#980]
**What topic do you wish to add?**
RDM in Cyprus: https://github.com/elixir-europe/rdmkit/blob/master/pages/national_resources/cy_resources.md 

**Are there existing pages in the RDMkit website related to the requested page?**
no

**Resources**
If there are there resources that could be utilised for writing the new page, please list them below:

**Context**
@aoulas requested a national page for Cyprus

**Comment by floradanna** [comment]
@aoulas 
Hi Anastasis, thank you for reaching out to the editors.

I have created an empty page for you here: https://github.com/elixir-europe/rdmkit/blob/master/pages/national_resources/cy_resources.md
You can now start editing this page and create your (draft) pull request.

More information can be found here: https://rdmkit.elixir-europe.org/github_way
Please, don't hesitate to contact us if you have further questions.

**Comment by Nazeeefa** [comment]
@aoulas I have provided the review for current content #979  :)
