### ISSUE TITLE
markdown display issue on page: Plant Phenomics

### ISSUE THREAD

**Issue by erlefloch** [elixir-europe/rdmkit#989]
I would like to report an issue on the Plant Phenomics page at `/plant_phenomics_assembly`. Description of the issue:
The drop-down lists of links "MIAPPE template resources" and "More information about PHIS" did display correctly on GitHub, but don't display correctly on the website. How to format it correctly ?

**Comment by bedroesb** [comment]
@erlefloch This is a problem that I am aware of and has to do with the Markdown parser and I did not yet find a solution for this. I kinda forgot about this.  think it would be better to take it out :/

**Comment by erlefloch** [comment]
alright, let's do so
